### ISSUE TITLE
Uniquely Identifying Foes on Combat Screen 

### ISSUE THREAD

**Issue by kspriv** [AlderArts/foe#187]
When you are attacked by say four Bandit(M)s it is a little difficult to know which one is up next in the running order.
Would it be possible to add the slot number at the end of the name so one can tell which is which? 

Link to original poster: http://forum.fenoxo.com/thread-11921.html

**Comment by kspriv** [comment]
I looked at it a bit and this looks easy enough to do. A couple minor questions for you and I'll do it in the morning:
-Should I always label enemies, or only label them when there's duplicates?

-Should I make it unique across all enemies, or unique across duplicates. (e.i. If there's two Human(M) and two Human(F). Should I label it Human(M) 1, Human(M) 2, Human(F) 1, Human(F) 2....OR Human(M) 1, Human(M) 2, Human(F) 3, Human(F) 4?).

**Comment by aldergames** [comment]
Perhaps the best is to always label them 1-4. Like so: Human(M) [3] etc. (number represents the position in enemy party, so it should always apply, even if all the mobs have unique names).

Another question... where should this be applied?
* Shown in the combat order - Yes
* Shown on portrait - I think no
* Shown on buttons - Again, I think no

This gets me thinking that perhaps the way to combine these number with the portraits and buttons is to use fixed positions. If you met four enemies, you would get four buttons for targetting, 1-4. Their positions would remain fixed even after they died (though they would be grayed out).

Pros: You always know exactly what and who you're attacking.
Cons: You can't do the 1 1 1 1 spam to clear combat.

Thoughts?

**Comment by kspriv** [comment]
Ah, I was going to toss the unique identifier on all 3 (was much easier to do :P). However, after looking at the result I'm leaning towards just displaying it in combat order and using fixed position for the other two, like you suggested. I'll submit this as a separate commit so you can look at that version yourself.

I'll do the fixed position version in another commit and have that submitted in a little bit. As for the con you mentioned these are all I can come up with as work arounds:
-Disabled buttons aren't counted for hotkeys. So pressing 1 will take the first NOT disabled option.
-Add a hotkey dedicated to taking the first not disabled option? ~shrug

**Comment by aldergames** [comment]
The buttons have fixed hotkeys, so the first workaround won't work.

**Comment by aldergames** [comment]
Remains to be seen how well this works... I already see some problems with it.
A) Current setup works for simpler encounters, but for things such as the intro demon and the bandits, I foresee problems if you remove an enemy in slot 1 and insert a new one. The new enemy ids would be [5, 2, 3, 4], without any real way of telling which one is which.
B) The fixed position buttons might be annoying in practice... we may have to revert that to how it was before. Pending more play testing.

**Comment by kspriv** [comment]
Oh, I wasn't aware that inserting a new enemy was a thing. In that case these are some possibilities:

-Use that unique name across all 3 displays (turn order/portrait/buttons). My first commit had that, so you can look at that if you want. My only big issue with it was the slot label on the portrait was big (since it was part of the entity.name). That could be changed easily enough though.

-Make the code that gives a list of enemies to the portrait/button generator smarter? I'm not sure what it's doing now, but my assumption would be it goes over the list of enemies in order and takes the first 4 valid enemies (e.g. not incapacitated) and sends them. If so, it shouldn't be a problem if a new enemy is introduced when one of them dies, because the new enemy should be after all the others in the enemy list.

e.g. Enemies: 1,2,3,4,5
-Enemy 2 dies
-Portraits reload from the list of enemies, Enemies: 1,3,4,5
-Same deal for buttons

This seems logical to me, unless I'm missing something?

-------------------------------------------

I agree that the button thing is a little annoying. I could get used to it, but I'm not sure if it's worth it when including the unique name on buttons removes the need for it.

If you're really against displaying unique names on buttons then we could try making the buttons themselves unique some how. Different skins for different slots. Could be distinguished with colors...a small number somewhere..etc? A lot of possibilities there.

**Comment by aldergames** [comment]
Yeah, actually you're right, the order isn't a problem (my bad). I use either AddMember() or SwitchIn() when adding new enemies, and those just append to the end of the list.

After your reasoning, I agree to try with using the unique name over the three displays. Thus, the buttons would go back to the way they were before.

**Comment by aldergames** [comment]
Think this solves the issue?

**Comment by kspriv** [comment]
Yep, I have no objections to it. It's the best way to solve the issue without negatively affecting what was there (and working well) already.

**Comment by aldergames** [comment]
Closing this down then. If we need to tweak it further, make a new one for the specific problem.
