### ISSUE TITLE
Program Launch Corruption Tuesday Jan 06 2015

### ISSUE THREAD

**Issue by Zharkhella** [AlderArts/foe#198]
I was playing FoE 0.3s:Roa from Fenoxo's Website on Monday Jan 05, 2015, and everything seemed to be working fine.  Yesterday and today (Wed Jan 07, 2015), the game launch appears to be corrupted.  This is a screen shot of the program when launched with the latest version of Firefox.

![Uploading FoE-Capture.PNG . . .]()

**Comment by aldergames** [comment]
Not getting an image here.

I tried booting up the game today (7 Jan) and there weren't any problems for me. Can you reply with whatever error you are getting?

**Comment by Zharkhella** [comment]
Ok.

Here is the image again.

Desc.  Looks like the start screen except that both the left and right
sides of the screen look like a 4x4 combat with all the images looking like
a male PC overlaid with Cavalcade cards, and the only button available is
the 'New Game' button.

I'm using Windows 7 Professional Service Pack 1 and Firefox 34.0.5.

That program loads correctly with IE 11.0.9600.17501, with Chrome 39.0.2171.95
m, with Safari 5.1.7 and with Opera 26.0.1656.60.

To my knowledge, the only change made to my computer was the application of
the latest Windows Defender update between Jan 05 computer shut down, and
Jan 06, Fall of Eden launch.

Z

**Comment by Zharkhella** [comment]
Also, I tried clearing my cache, and that did not resolve the issue.

Z

**Comment by aldergames** [comment]
Still no image for me, but I recognize the error. I'm unable to reproduce it on my comp (same Firefox version).

Can you run the game with Firefox and activate the developer console? Shift+F2 by default I think. See if there are any error messages and copy them exactly here.

**Comment by aldergames** [comment]
If you want to give the image another go, upload it to imgur or a similar site and post the link. Whatever you're doing doesn't seem to be working.

**Comment by Zharkhella** [comment]
Hi,

I noticed there is a new build up and available (Fall of Eden 0.3t:
Burrows, pt.2 + Cveta).  However I am still have the same issue with
Firefox (see Screen Shot).  Any idea what may be wrong on my end?  The game
is loading just fine in IE, Safari, Opera and Chrome.

I'm still not sure what happened on the 6th to cause this.

**Comment by aldergames** [comment]
THERE IS NO SCREENSHOT TO SEE.

**Comment by Zharkhella** [comment]
FYI:

Whatever the issue was... it appears to be resolved now.  When I load Fall
of Eden in Firefox the screen comes up as it does in the other browsers
with all the buttons visible.

Z
