### ISSUE TITLE
Offline saves

### ISSUE THREAD

**Issue by aldergames** [AlderArts/foe#202]
Old, old issue, with two parts:

1. Save to file. This doesn't work on any browser in offline mode due to the js sandbox. Only way this works regularly is through a php component creating the file and allowing you to download it. The "save to text" is a way to try and get around this problem, but it's not ideal.
2. Internet Explorer. FoE uses webstorage (localstorage[]) to do regular saves. This isn't available for offline IE for some reason.

If someone with more web-dev experience than me could offer some suggestions, that'd very much be appreciated.

**Comment by paradj00** [comment]
perhaps in "save to text" dialog a "select all" and "copy to clipboard" buttons would help.

**Comment by PowerOfVoid** [comment]
My Firefox can't use "normal" saves either, but Chromium can.
