### ISSUE TITLE
some bug and typo

### ISSUE THREAD

**Issue by trixymoon** [AlderArts/foe#205]
lagon.js line 522

if(player.FirstVag()) => I think was player.FirstCock() ?

__________

roa.js line 467

“They smell delicious...” -> [ItThey]

___________

Capacity rewrite.

I believe it is appropriate to change the save game property ass and vagina "cap", or even a virgin character, is described as "loose" ass / vagina 
_________

cveta.js
missing space line at 193:
 "placate.This"

missing ” at the end of the lines: 187, 193, 195, 204, 206, 416, 631, 679, 687, 689, 714, 718, 276, 728, 730, 758, 790, 792, 824, 833, 835, 878, 880, 882, 914, 916, 918.

**Comment by aldergames** [comment]
Fixed everything except for the capacity issue. Put that in the main capacity rewrite issue.

**Comment by trixymoon** [comment]
Good, for the capacity rewrite, I do not know if I was clear in explaining the problem... 
however I was referring to the base capacity for the ass and vagina for the player, kiakay and Rosalin.
Can you solve the problem using save version forcedly setting the correct new value?
Like:
<pre>if gameCache.version &lt; 21 {
  player.vagina.capacity.base = 5
  player.ass.capacity.base = 4
// the same for rosalin and kiakay
}
</pre>

As always, sorry for my bad english...

**Comment by aldergames** [comment]
Aye, I understood it.
