### ISSUE TITLE
[Fall of Eden 0.3v2: Ophelia (Terry save fix)]  Stretching/Capacity Bugs with Terry

### ISSUE THREAD

**Issue by NotYouNorI** [AlderArts/foe#209]
While i have been playing with the newly added stretch/capacity feature in FoE and have noticed how every time i visit either Jeanne's tower or the rented room in the inn in rigard Terry's capacity/looseness returns to default or at least is reduced considerably (a.k.a. his/her sex options grey out)

I have also found that while using a canid strapon on Terry anally works just fine, the scene where the PC uses the strapon on Terry vaginally describes the PC having a vagina, even though my PC is a twin-dicked male.
Furthermore, said vaginal sex option with a canid strapon doesn't seem to have any effect on Terry as neither does any sort of stretching occur nor is his/her LP drained.

**Comment by aldergames** [comment]
Note to self: examine and tweak the logic behind stretching - it doesn't seem to be working as intended.
