### ISSUE TITLE
Terry lacks a F/F scene

### ISSUE THREAD

**Issue by aldergames** [AlderArts/foe#215]
As title says. Can cause a softlock, so should be fixed.

**Comment by paradj00** [comment]
has this been fixed?
i see the leadernote says so, but, pet scene still leaves no option
 also is last git supposed to 3y or is it still 3x?
 gitzip download is still 3x (03082015)
tried with different browsers/caches
i could be way off base... but, prob may stem from incomplete physiological save stats and tf.js..
only tryin to help. Thanx Alder!

**Comment by aldergames** [comment]
This doesn't have anything to do with pet. This is Terry F/F sex.

The version only updates when I make a new release, so consider the github changelog a WIP.

**Comment by paradj00** [comment]
ooops! ..Sorry! .. i misunderstood what F/F stood for... my bad...

**Comment by aldergames** [comment]
Partly fixed by 5d3d716da04f265704140ffc02f2843fba5e452f

**Comment by aldergames** [comment]
(Leaving open until the scene is completed)
