### ISSUE TITLE
I have fuck Lagon to lvl 9 twice

### ISSUE THREAD

**Issue by Akhter13** [AlderArts/foe#218]
Lagon gains 4 sex exp.

Lagon gains a sex level! Now at 9.

Lagon's butt has become loose.

Lagon's sex lvl and anal tightness reset every time you load

**Comment by aldergames** [comment]
Huh. The sex level is understandable. It should only really show in debug mode anyways, and it has no actual impact. Anal tightness shouldn't reset tho, will have to look into that. Can you send me your save file?

(Anal tightness will be restored over time, so make sure it isn't due to this first)

**Comment by Akhter13** [comment]
I have done some testing it doesn't happen if I open a new window and load a saved game.It only happens if I reboot the computer and then load the file.It does not appear to be a corruption of a single save as it first appeared with a save I have subsequently saved over.Additional info I was in debug mode as I was working on blue ball.
I apologize that I can not provide the save file, it is a task beyond my understanding. (I stopped trying to keep up with what was going on under the hood at the change over from MS-Dos to Windows 3.0, which happened to be when I got kids).
Find text to support

You tell him that you’ve come here to use him. He was very sexually active when he was in power; you’re sure he understands what it feels like to have an itch that needs scratching.

“Let’s get it over with then,” he says, just a bit too quickly for it to sound like an offhand remark. The king adjusts himself ever so subtly to show you his huge erection. “How will you have me today?”

You smile proudly. That’s a good boy; he’s starting to learn his place, isn’t he? Why, you might even reward him by letting him cum this time, since he’s on such good behavior. Wouldn’t he like that? Lagon gives you a sidelong glance and the faintest of nods.

Then again, does it really matter to him at this point? He’s turned into such an obedient little slut, eager to be used however his mistress wants. No wonder he went and gave his wife such a huge dick of her own; he must just love it when she deigns to fuck his little ass the way he used to fuck hers.

Lagon simply scowls at you, but otherwise doesn’t offer any response. All he does is sigh in resignation. “Are you going to continue with this pointless tirade or get on with it? I’d like to get off today if you don’t mind,” he says, softly stroking his erection.

Although he still tries to act like he has some semblance of defiance left in him, the trembles of anticipation sweeping through his body and the way his eyes keep darting to your crotch show the truth. It’s nothing but a hollow facade, and you both know it.

Lagon clearly wants this as much as you do. So, what should you do with your captive slut today...
You quickly undress, then tell Lagon to be a good boy and spread his legs for you.

Lagon obediently spreads his legs, letting you gaze at his cock as he holds his legs up to give you access.

Very good, you praise him. Obedient and no talking back - you can see Lagon is going places.

He furrows his brow, but rather than talking back in the usual display of defiance, he simply sighs. “Let’s just get this over with. You’re going to use me no matter what I say, so what’s the point?”

Yes, you will. It’s good to see that he finally understands his position.

No sense beating around the bush any longer. You go to your belongings and fetch some lube.

First you apply a generous helping to one of your cocks. Then you return to Lagon and order him to lift his legs higher so you can access his tailhole.

He does as you ask and you apply another helping to your hands, then smear the slick fluids around his ass.

Lagon grunts in discomfort as you insert your fingers to massage his butt, stretching him out and lubing his entrance in preparation for his penetration.

Once you’re done, you put away the lube and position yourself between his legs. Without thinking, you let your immense girl-cock flop over his own shaft and balls, gently frotting him.

You watch as Lagon swallows audibly. It’s clear that he’s intimidated by your size, and considering how his own member is throbbing against yours, you’d say even a little excited.

You promise him that you’ll be gentle.

DEBUG: Lagon.slut 67 -> 68 (max: 100)



Pulling back, you prod his butt with your immense clit-cock, until you manage to nestle it against his rosebud, then you begin pushing in.

Despite your initial stretching he’s still as tight as the virgin he is. It takes quite a bit of work just to push your tip past his resisting sphincter. And even after you manage to do so, the lagomorph continues to constrict you, trying his best to push out the intruder. You have no intention of stopping, however.

Lagon grunts in discomfort as you spread him like he was never spread before. His face is a grimace of pain, but beneath that you can see a spark of unwanted pleasure. He’s enjoying himself.



Lagon gains 4 sex exp.



Tracii gains 4 sex exp.

Once you manage to bury yourself as deep as you can, you hold yourself there, letting him get used to your girth and size before you start moving.

Lagon tries his best to resist you, fighting his groans and grunts of pleasure, but his effort is futile. You’re an expert at this and can play his body like a well-tuned instrument. A little adjustment here, a small twist there, some occasional grinding, and the former king’s pride crumbles beneath the barrage of pleasure.

The lagomorph moans whorishly, no longer caring about maintaining his facade. He bucks back into your thrusts, his ass clings to your cock like a long lost lover, his legs wrap around you to allow to thrust ever deeper. It’s truly a sight to see. His face is twisted into an expression of the purest pleasure, tongue lolling out as you force him to moan for you.

His own cock throbs in tune with your thrusts. Each pump earning a spurt of pre. If only you could capture this moment… the former king, reduced to nothing more than a sex toy, moaning in bliss as your immense girl-cock brings him ever closer to his pinnacle. Lagon is going to cum - you can tell by the way his shaft is throbbing, no longer bouncing around due to how hard it’s become. His balls are already churning with his impending climax.

If you wanted to stop him from cumming, now would be the time to act.
 

     On Sunday, 8 March 2015, 0:10, aldergames <notifications@github.com> wrote:
   

 Huh. The sex level is understandable. It should only really show in debug mode anyways, and it has no actual impact. Anal tightness shouldn't reset tho, will have to look into that. Can you send me your save file?(Anal tightness will be restored over time, so make sure it isn't due to this first)—

**Comment by trixymoon** [comment]
Lagon sex stats aren't saved on json. So whenever you restart the browser, Lagon seems to be virgin  because "lagon.sex.rAnal == 0" is true again.
I'm unsure about the 'blueball' thing too, in fact, even denying him many times in a row, don't seems that I can trigger the blue ball status

**Comment by aldergames** [comment]
Ahh! Of course! Thanks trixy!

**Comment by Akhter13** [comment]
I have trigger blue ball it seemed to occur immediately after midnight on the day after denying him and didn't stop when I let him cum will test to see if you need to wait till next day
