### ISSUE TITLE
Failure to Launch

### ISSUE THREAD

**Issue by Kitsunenomenka** [AlderArts/foe#219]
I've been unable to run FoE offline for quite some time (0.2w2 is the earliest I can find on my drive) and have been unable to run it online either from somewhere in the 0.3 range. I've tried running all versions including releases through 0.3x2 and the master files from this site. I use Firefox as my browser and I'm running on an XP machine. When I attempt to load the game, the following is displayed under the java script portions of both the web and browser consoles for debugging:

SecurityError: The operation is insecure. foe.js:9377:0

This is the only thing that pops up for any version I attempt. All I get on the screen is black. I've tried using the last version of Java 7 (which is supposedly the last which will work with XP) as well as the latest version of Java 8. Firefox version is 36.0.1, but this has been happening for quite some time now. Thanks for your time and attention.

**Comment by aldergames** [comment]
Java version makes no difference (javascript and java are different things). I run the game both online and offline on Firefox 36.0.1. It would be nice if you could download the entire source from here on github to figure out which line is actually insecure. I'm suspecting something to do with webstorage, but we'll see.

**Comment by Kitsunenomenka** [comment]
I do have the source from here, now how do I go about viewing line by line activity?

**Comment by aldergames** [comment]
That line is indeed where I check for localstorage:
https://github.com/AlderArts/foe/blob/master/js/main.js#L9

Not sure what would cause this... perhaps you have some strict setting on your firefox. Try the newest Chrome and see if you get the same result.

**Comment by Kitsunenomenka** [comment]
Well, no problem with Chrome. Still, I don't plan on using Chrome at all for any non-diagnostic purpose. I'll look through my Firefox extensions, I suppose.

**Comment by Kitsunenomenka** [comment]
All right, I've tracked down the issue. It seems to have been around since at least 2012, and the bug is referenced here:
https://bugzilla.mozilla.org/show_bug.cgi?id=748620

Apparently, Mozilla decided to tie localStorage permissions to cookie permissions. The option to prompt for third-party cookie expiration, however, returns the same value as rejecting/disabling cookies for the purposes of localStorage permissions, regardless of whitelisting. It appears this behavior was itself implemented as the solution to this bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=341524

So, there's that explained, at least. I'll leave off closing the issue just now in case you wish to respond. Also, I haven't worked with JavaScript for quite a while, so my interpretation of what I read and presumptions of code behavior could be wildly inaccurate.

**Comment by aldergames** [comment]
If you can still reproduce the error, try if it persists with the latest code.

**Comment by Kitsunenomenka** [comment]
That does seem to fix it, thanks!
