### ISSUE TITLE
Question regarding Terry's Oral scene

### ISSUE THREAD

**Issue by Havrrics** [AlderArts/foe#220]
I could be totally confused by all the text in the changelog for it and that all may not yet be in the game (which I suspect is the case), but on the off chance that it is all suppose to be in the game, all I'm getting when I try it is this, 

"“Gee, Lucius. That almost makes me think you don’t like to hear me speak,” she replies, teasing. “So, what kind of tasty treat are you gonna give me now?”

With a mischievous grin, you make a show of contemplating your answer.

PLACEHOLDER"

Is this intentional?

**Comment by aldergames** [comment]
Yeah, the BJ scene isn't coded yet. I implemented what there was anyways, since it solved a bigger problem.

**Comment by Havrrics** [comment]
I see, thanks for clearing that up and keep up the good work as always.
