### ISSUE TITLE
Layla sex scene question

### ISSUE THREAD

**Issue by CalmKhaos** [AlderArts/foe#221]
I'm trying out the latest version on github and noticed that I am unable to proceed any further with Layla after approaching the topic of sex. The button is not greyed out, but it does not do anything. I have her in my party and was wondering if that may be a reason why I am unable to interact with her in that manner.

**Comment by aldergames** [comment]
Hmm... I'd say that there's a bug there. I'll look into it after sleep. I haven't tested Layla's stuff that much yet, since there's still stuff left to code before she's ready for a release.

**Comment by CalmKhaos** [comment]
Sounds good. I just figured to bring it to your attention.
