### ISSUE TITLE
Parsing issue during Layla scene

### ISSUE THREAD

**Issue by CalmKhaos** [AlderArts/foe#222]
Firstly, thank you for fixing the issue that was present with the scene.

Sadly, I have come across another little issue during the sex scene. This is within the tailcock scene - taste option. It showed a parsing issue. I will paste the text:

-The thick gelatinous goo floods your mouth, forcing you to swallow. It tastes... quite enticing, actually. It burns all the way down to your stomach, but it’s a pleasant burn, like a fine liquor. It fills your belly with warmth, a surge of heat that spreads along your body.

It concentrates itself in your loins, a burning that makes you moan with need. ['gen' couldn't be parsed] as lust swirls through your veins. You pant heavily at the warmth inside of you.-

If I may add another issue found to this:
When asked by Layla when she tells you about her nipples and asks if you want to try them, selecting 'No' seems to keep the same dialog choices available and you can't proceed without selecting one of the other options available.

**Comment by aldergames** [comment]
Thanks, this commit should hopefully fix that.
