### ISSUE TITLE
Terry Get Oral issue

### ISSUE THREAD

**Issue by CalmKhaos** [AlderArts/foe#225]
I seem to be losing some relationship points with Terry on this scene despite that I have reached the cap. I caught wind of this issue over on Fenoxo forums. I used debug mode to check and have copied the last few lines of the scene:

The vixen coughs, trying her best to catch her breath.

“It’s always a thrill with you isn’t it, Ky? I love your pussy, but someday I know you’re going to hold on too long and smother me with your cunt. Though I suppose there’s worse ways to go,” Terry teases, chuckling at the idea.

Well, you have no intention of letting her go that way anytime soon. What would you do without your favorite pussy-licker?

“What indeed, ya huge perv!”

DEBUG: Terry.relation 100 -> 99 (min: 0)

**Comment by aldergames** [comment]
Yeah, this defo sounds like a bug. I'll look into it.
