### ISSUE TITLE
Gwendy doesn't leave party

### ISSUE THREAD

**Issue by kspriv** [AlderArts/foe#226]
Gwendy can still be switched in to your party after handling the Layla issue if you go back to the Tent. I assume this is unintentional.

**Comment by aldergames** [comment]
Really? With the latest github release? Cause I can't reproduce it anymore.

**Comment by kspriv** [comment]
Sorry, it's not the latest release. It's the latest release on fenoxo.

-I can trigger the event where you go fight Layla, which causes Gwendy to temporarily join my party.
-After finishing said event, I can go to the 'party' screen back at camp and 'switch in' Gwendy.

**Comment by aldergames** [comment]
Yup, it is fixed: https://github.com/AlderArts/foe/issues/224
