### ISSUE TITLE
Cock descriptions seem off in Cheat Cavalcade

### ISSUE THREAD

**Issue by Akhter13** [AlderArts/foe#228]
PC has duo of human girl cocks (no barbs or sheaths) gets the following

Ignoring the wolf, you grasp one of your duo of immense clit-cocks and press it against his back door. The barbed head of your gargantuan, knotted, sheathed feline dong popping inside him does wonders for shutting him up. Unless you count the loud moaning.

**Comment by aldergames** [comment]
That sounds weird... try to see if it's still there. I tweaked some logic, but it shouldn't do that even despite that.

Barbed triggers if you have a cat cock. Can you print out you full appearance (or rather, all your cocks)?

**Comment by CalmKhaos** [comment]
Sure. Here is my full description in the game (I did edit my race and some other features):

You are a hermaphrodite dragon, 175cm tall and weighing around 68kg. You have olive scales. You are wearing simple cloth robe. You are wearing a pair of simple bronze leggings. You are wielding a whip made of vines.

You have a face. Your two purple demonic eyes observe the surroundings. A pair of fuzzy vulpine ears sticks out from your long, wavy black hair.

On your back, you have a long, scaled draconic tail.

You have arms and legs.

You have thick hips, and a squeezable tush.

You have a pair of large globes.

You have a big feline clit-cock, 15 cms long and 4.5 cms thick.

You have a very flexible cooch.

Cum: 5.00 / 5.00

Milk: 0.00 / 18.00

You have a very flexible ass.

**Comment by Akhter13** [comment]
You are a herm human, 175cm tall and weighing around 68kg. You have white skin. You are wearing stylish clothes, with an alluring cut. You are wearing a pair of simple bronze leggings. You are wielding a dagger fashioned out of a Gol claw.

You have a human face with smooth skin. Your two purple eyes observe the surroundings. A pair of ears sticks out from your short straight blonde hair. 

You have arms and legs.

You have wide hips, and a gropable rump.

You have a pair of hefty tits.

You have a brace of two girl-cocks.

You have an immense human girl-cock, 54 cms long and 5 cms thick.

You have an enormous human member, 35 cms long and 5 cms thick.

Beneath your other genitalia, a duo of well-proportioned throbbing balls hang.

You have a gaping slit.

Cum: 10.88 / 20.00

Milk: 13.00 / 13.00

You have a slutty anal opening.

DEBUG: relation: 22

DEBUG: subDom: 75

DEBUG: slut: 75
 



     On Sunday, 29 March 2015, 15:03, aldergames <notifications@github.com> wrote:
   

 That sounds weird... try to see if it's still there. I tweaked some logic, but it shouldn't do that even despite that.Barbed triggers if you have a cat cock. Can you print out you full appearance (or rather, all your cocks)?—

**Comment by aldergames** [comment]
And? Does it still do the same thing?

**Comment by Akhter13** [comment]
Just tried again and
“Just take me already!” Cale whines, eager to get some dick. He tries pushing back against you, forcing your cocks to rub against his sensitive slutty anal opening.

Ignoring the wolf, you grasp one of your duo of immense girl-cocks and press it against his back door. The barbed head of your gargantuan, sheathed feline prick popping inside him does wonders for shutting him up. Unless you count the loud moaning.
 



     On Sunday, 29 March 2015, 17:29, aldergames <notifications@github.com> wrote:
   

 And? Does it still do the same thing?—

**Comment by aldergames** [comment]
Doesn't make much sense to me, the scene should take the biggest cock you currently have and apply those stats. There's nothing strange about the cock desc code. Post you save file?

**Comment by kingpingpong** [comment]
Are you running the compile script and then opening the foe.html file in the build folder afterwards? Might make a difference?

**Comment by Akhter13** [comment]
I hope this helps
Debug1940/19401673/167378/15001425/14251253/1422865/11691619/16191227/12271212/12121345/13451272/1272175/1302Next{"version":24,"time":{"year":891,"season":2,"day":8,"hour":2,"minute":50},"flags":{"LearnedMagic":3,"Portals":0,"IntroLostToImps":1,"IntroToldUruAboutMirror":0,"IntroFuckedUru":1,"IntroFuckedByUru":0,"IntroOutset":0,"TalkedToTownGuard":0,"FarmFound":null,"FarmLockout":0,"OutlawsRep":null,"NagaVenom":0,"Moth":1},"build":"Fall of Eden 0.3y: Layla","rigard":{"flags":{"Visa":1,"CityHistory":1,"RoyalAccess":1,"RoyalAccessTalk":2,"TalkedStatue":1,"TailorMet":1,"BuyingExp":3,"Scepter":0},"Krawitz":{"Q":4,"F":169,"Work":2,"Duel":3},"Brothel":{"Visit":1,"MStrap":0},"CW":{"Visit":0},"LB":{"Visit":1,"Orvin":1,"OTerry":0,"Orvin69":0,"CityTalk":1,"RotRumor":2,"Efri":0,"RoomNr":0,"RoomComp":0,"Tea":1,"Lizan":1,"Elven":0,"Fairy":0,"Red":1},"LBroom":{}},"farm":{"coin":18200,"flags":{"Visit":1}},"burrows":{"flags":{"Access":8,"BruteTrait":2,"HermTrait":2,"BrainyTrait":2,"Felinix":1,"Lacertium":1,"Equinium":1}},"glade":{"flags":{"Visit":2}},"treecity":{"flags":{"Access":0}},"player":{"body":{"tone":"0.10","mass":"0.00","height":"175.00","weigth":"68.00","fem":"0.80","head":{"race":"0","col":"0","mouth":{"cap":"30.00","ton":{"race":"0","col":"0"},"tonL":"7.00"},"hair":{"race":"0","col":"15","len":"5.00","style":"0"},"eyes":{"race":"0","col":"17","count":"2"},"ears":{"race":"0","col":"0"}},"torso":{"race":"0","col":"0","hip":"8.00"},"cock":[{"len":"54.00","thk":"5.00","race":"0","col":"0","type":"1"},{"len":"35.00","thk":"5.00","race":"0","col":"0"}],"balls":{"size":"3.00","cum":"7.70","cumP":"1.50","cumC":"14.00","fer":"0.50","race":"0","col":"0","count":"2"},"vag":[{"cap":"10.00","str":"1.45","wet":"1.00","virgin":0,"col":"18","clitT":"0.50","clitL":"0.50","mstr":"1.00"}],"ass":{"cap":"9.00","str":"1.50","virgin":0,"size":"8.00","mstr":"1.00"},"breasts":[{"size":"13.00","nipC":"1","col":"0","race":"0","nipThk":"0.50","nipLen":"0.50","aerS":"2.00","nipType":"0"}],"arms":{"race":"0","col":"0","count":"2"},"legs":{"race":"0","col":"0","count":"2"}},"name":"Tracii","exp":"324","points":"0","exp2lvl":"1298","lvl":"26","sexp":"422","sxp2lvl":"3840","slvl":"8","alvl":"1","curHp":"1940.0","maxHp":"100.0","curSp":"1673.0","maxSp":"30.0","curLust":"78.6","maxLust":"30.0","str":"15.0","sta":"14.0","dex":"40.0","inte":"30.0","spi":"30.0","lib":"30.0","cha":"40.0","maxHpG":"15.0","maxSpG":"10.0","maxLustG":"5.0","strG":"4.2","staG":"4.0","dexG":"3.9","inteG":"4.6","spiG":"3.9","libG":"3.1","chaG":"4.1","subDom":"75","slut":"75","rel":"22","recipes":["lago0","felin0","rept0","equin0","bov0","fox0","naga0","wolf0","moth0"],"effects":[],"jobs":{"Fighter":{"lvl":8,"exp":14},"Scholar":{"lvl":8,"exp":3},"Courtesan":{"lvl":8,"exp":12},"Bruiser":{"lvl":6,"exp":197},"Ranger":{"lvl":3,"exp":2},"Mage":{"lvl":3,"exp":3},"Mystic":{"lvl":5,"exp":241},"Healer":{"lvl":3,"exp":10},"Hypnotist":{"lvl":6,"exp":796}},"curJob":"Bruiser","wep":"dag1","toparm":"cloth0","botarm":"pants1","acc1":"book0","acc2":"head0","toy":"strapon4","preg":{"gr":"1.00","f":"0.30"},"lact":{"lact":1,"lactR":0,"milk":13,"milkP":0,"milkC":0},"flags":{"startJob":1},"sex":{"rBlow":64,"gBlow":94,"rCunn":21,"gCunn":26,"rAnal":152,"gAnal":599,"rVag":63,"gVag":312,"sired":25,"birth":22},"perks":["vir0","bre0","fer0"]},"kiakai":{"body":{"tone":"0.00","mass":"0.00","height":"165.00","weigth":"52.00","fem":"0.20","head":{"race":"10","col":"0","mouth":{"cap":"30.00","ton":{"race":"10","col":"0"},"tonL":"7.00"},"hair":{"race":"10","col":"6","len":"15.00","style":"0"},"eyes":{"race":"10","col":"17","count":"2"},"ears":{"race":"10","col":"0"}},"torso":{"race":"10","col":"0","hip":"3.00"},"cock":[{"len":"20.00","thk":"3.00","race":"0","col":"0"}],"balls":{"size":"3.00","cum":"16.00","cumP":"1.00","cumC":"10.00","fer":"0.30","race":"10","col":"0","count":"2"},"vag":[{"cap":"5.00","str":"1.00","wet":"1.00","virgin":1,"col":"18","clitT":"0.50","clitL":"0.50","mstr":"1.00"}],"ass":{"cap":"4.00","str":"1.00","virgin":0,"size":"3.00","mstr":"1.00"},"breasts":[{"size":"5.00","nipC":"1","col":"0","race":"10","nipThk":"0.50","nipLen":"0.50","aerS":"2.00","nipType":"0"}],"arms":{"race":"10","col":"0","count":"2"},"legs":{"race":"10","col":"0","count":"2"}},"name":"Kia","exp":"11","points":"0","exp2lvl":"1298","lvl":"26","sexp":"377","sxp2lvl":"480","slvl":"5","alvl":"0","curHp":"1425.0","maxHp":"80.0","curSp":"1253.6","maxSp":"50.0","curLust":"865.7","maxLust":"20.0","str":"12.0","sta":"13.0","dex":"16.0","inte":"18.0","spi":"20.0","lib":"13.0","cha":"13.0","maxHpG":"10.0","maxSpG":"5.0","maxLustG":"5.0","strG":"3.1","staG":"2.4","dexG":"3.1","inteG":"4.6","spiG":"3.3","libG":"2.3","chaG":"3.3","subDom":"-49","slut":"100","rel":"100","recipes":[],"effects":[],"jobs":{"Acolyte":{"lvl":8,"exp":2},"Fighter":{"lvl":5,"exp":60},"Scholar":{"lvl":3,"exp":8},"Courtesan":{"lvl":3,"exp":109},"Mage":{"lvl":3,"exp":5},"Mystic":{"lvl":3},"Healer":{"lvl":3,"exp":14},"Hypnotist":{"lvl":7,"exp":1232}},"curJob":"Hypnotist","wep":"staff1","toparm":"robe1","botarm":"pants0","acc1":"ear0","acc2":"ear0","toy":"strapon2","preg":{"gr":"1.00","f":"0.30"},"lact":{"lact":1,"lactR":0,"milk":5,"milkP":0,"milkC":0},"flags":{"RotGeo":1,"RotPeople":1,"RotFactions":1,"RotElfCulture":1,"RotElfParents":1,"RotElfChild":1,"RotPrHier":2,"RotPrDisc":2,"RotPrAct":6,"RotPrYrissa":2,"RotPrAria":1,"RotPrMeeting":1,"InitialGender":1,"Attitude":-1,"AnalExp":201,"Sexed":214,"TalkedSex":3,"SexPitchAnal":1,"SexCatchAnal":1,"TalkedWhyLeave":1,"TalkedPriest":1,"TalkedElves":1,"TalkedAria":1,"TalkedUru":1,"TalkedUruDA":1,"TalkedStatue":1},"sex":{"rBlow":3,"gBlow":61,"rCunn":26,"gCunn":10,"rAnal":123,"gAnal":35},"perks":[]},"miranda":{"name":"Miranda","exp":"0","points":"0","exp2lvl":"51","lvl":"8","sexp":"86","sxp2lvl":"480","slvl":"5","alvl":"0","curHp":"290.0","maxHp":"100.0","curSp":"115.0","maxSp":"10.0","curLust":"203.0","maxLust":"50.0","str":"23.0","sta":"19.0","dex":"19.0","inte":"12.0","spi":"11.0","lib":"24.0","cha":"14.0","maxHpG":"10.0","maxSpG":"5.0","maxLustG":"6.0","strG":"1.7","staG":"1.4","dexG":"1.1","inteG":"1.0","spiG":"1.2","libG":"1.5","chaG":"1.1","subDom":"-64","rel":"73","effects":[],"jobs":{"Fighter":{"lvl":3}},"curJob":"Bruiser","wep":"swrd2","toparm":"chest1","body":{"balls":{"size":"6.00","cum":"17.00","cumP":"4.00","cumC":"5.00","fer":"0.30"},"vag":[{"cap":"5.00","str":"1.00","wet":"1.00","virgin":0}],"ass":{"cap":"4.00","str":"1.00","virgin":0}},"flags":{"Met":3,"Herm":1,"Attitude":1,"Thief":1,"RotGuard":3,"Forest":1,"Floor":2,"Footjob":28,"Bruiser":2,"Dates":14,"bgRot":5,"bgRotMax":4,"ssRot":2},"sex":{"rBlow":52,"gBlow":3,"rAnal":33,"gAnal":67,"rVag":28}},"terry":{"body":{"balls":{"size":"5.00","cum":"20.00","cumP":"1.00","cumC":"10.00","fer":"0.30"},"vag":[{"cap":"5.00","str":"1.00","wet":"1.00","virgin":0}],"ass":{"cap":"4.00","str":"1.00","virgin":0}},"lact":{"lact":1,"lactR":1,"milk":10,"milkP":3,"milkC":0},"preg":{"gr":"1.00","f":"0.30"},"flags":{"Met":3,"Saved":4,"Skin":51,"BM":1,"xLick":18,"TF":15,"TFd":11,"xLact":4,"caFirst":1,"breasts":4,"lact":1,"vag":2,"cock":1},"sex":{"rBlow":32,"gCunn":2,"rAnal":87,"gAnal":5,"rVag":81,"birth":25},"name":"Terry","exp":"807","points":"0","exp2lvl":"1082","lvl":"25","sexp":"226","sxp2lvl":"480","slvl":"5","alvl":"0","curHp":"1619.0","maxHp":"50.0","curSp":"1227.0","maxSp":"60.0","curLust":"1212.0","maxLust":"50.0","str":"13.0","sta":"10.0","dex":"24.0","inte":"15.0","spi":"13.0","lib":"15.0","cha":"20.0","maxHpG":"15.0","maxSpG":"6.0","maxLustG":"5.0","strG":"4.0","staG":"3.2","dexG":"5.3","inteG":"2.0","spiG":"1.8","libG":"2.0","chaG":"1.9","slut":"100","rel":"100","effects":[],"jobs":{"Fighter":{"lvl":8,"exp":2},"Rogue":{"lvl":8,"exp":11},"Ranger":{"lvl":5,"exp":38},"Scholar":{"lvl":3,"exp":10},"Courtesan":{"lvl":5,"exp":44}},"curJob":"Ranger","wep":"whip1","toparm":"chest3","botarm":"pants2","acc1":"ear0","acc2":"ear0","toy":"strapon3"},"momo":{"rel":"25","body":{"vag":[{"cap":"5.00","str":"1.00","wet":"1.00","virgin":1}],"ass":{"cap":"4.00","str":"1.00","virgin":1}},"flags":{"Met":3,"tSelf":1,"tFamily":2,"tCook":1,"tSkills":1},"sex":{},"wTime":{}},"lei":{"flags":{"Met":4,"ToldOrvin":1},"timeout":{}},"twins":{"rumi":{"rel":"8","flags":{}},"rani":{"rel":"12","flags":{}},"flags":{"Met":2,"SexOpen":0},"Ttime":{}},"room69":{"flags":{}},"maria":{"virgin":1,"avirgin":1,"rel":"3","flags":{"Met":1}},"chief":{"rel":"30","flags":{"Met":1}},"rosalin":{"body":{"tone":"0.00","mass":"0.00","height":"155.00","weigth":"49.00","fem":"0.60","head":{"race":"0","col":"0","mouth":{"cap":"30.00","ton":{"race":"0","col":"0"},"tonL":"7.00"},"hair":{"race":"0","col":"19","len":"5.00","style":"0"},"eyes":{"race":"2","col":"4","count":"2"},"ears":{"race":"2","col":"13"}},"torso":{"race":"0","col":"8","hip":"4.00"},"back":[{"race":"2","col":"13","type":"2","count":"1"}],"balls":{"size":"3.00","cum":"5.00","cumP":"1.00","cumC":"5.00","fer":"0.30","race":"0","col":"0","count":"0"},"vag":[{"cap":"5.00","str":"1.00","wet":"1.00","virgin":0,"col":"18","clitT":"0.50","clitL":"0.50","mstr":"1.00"}],"ass":{"cap":"4.00","str":"1.00","virgin":0,"size":"6.00","mstr":"1.00"},"breasts":[{"size":"10.00","nipC":"1","col":"0","race":"0","nipThk":"0.50","nipLen":"0.50","aerS":"2.00","nipType":"0"}],"arms":{"race":"0","col":"8","count":"2"},"legs":{"race":"0","col":"8","count":"2"}},"preg":{"gr":"1.00","f":"0.30"},"lact":{"lact":1,"lactR":0,"milk":10,"milkP":0,"milkC":0},"flags":{"PrefGender":1,"Met":1,"AlQuest":3,"PastDialog":4,"Felinix":1,"Equinium":1,"Lacertium":1,"Nagazm":1,"Bovia":1,"Lobos":1,"Vulpinix":1,"Lepida":1},"rel":"32"},"wolfie":{"virgin":0,"slut":"100","rel":"100","flags":{"Met":4,"Met2":3,"Sexed":1,"Rogue":3,"sneakAtk":1,"trickBJ":3,"xOut":37,"xedOut":1,"cLoss":10,"cCheat":1,"eBlow":10,"rotPast":4,"maxPast":4,"rosPast":1,"shop":106847},"sex":{"rBlow":7,"gBlow":7,"gCunn":5,"rAnal":49,"gAnal":1}},"estevan":{"body":{"ass":{"cap":"4.00","str":"1.00","virgin":1}},"flags":{"Met":1,"Ranger":1,"Cheat":3,"cav":2,"Gay":7}},"magnus":{"flags":{"Met":1,"Talked":1,"Sexed":1,"Teach":3,"Confronted":1},"sex":{"rBlow":1,"gAnal":1,"gVag":1}},"lagon":{"slut":"94","rel":"-5","body":{"ass":{"cap":"4.00","str":"1.00","virgin":0}},"flags":{"Usurp":26,"Deny":1},"sex":{"rAnal":7},"bbTim":{}},"gwendy":{"subDom":"-15","rel":"50","flags":{"Met":1,"Market":2,"Toys":1,"WorkMilked":53,"WorkFeed":67,"WonChallenge":33,"LostChallenge":20,"ChallengeWinScene":6,"ChallengeLostScene":3},"sex":{"gCunn":2,"rAnal":36,"rVag":10}},"adrian":{"body":{"ass":{"cap":"4.00","str":"1.00","virgin":1}},"subDom":"3","flags":{"Met":1}},"danie":{"body":{"vag":[{"cap":"5.00","str":"1.00","wet":"1.00","virgin":1}],"ass":{"cap":"4.00","str":"1.00","virgin":1}},"slut":"5","rel":"50","flags":{"Met":1}},"fera":{"avirgin":0,"virgin":0,"rel":"100","nexTim":{},"shopTim":{},"cityTim":{},"fonTim":{},"timeout":{},"flags":{"Met":1,"Mom":3,"Blowjob":1,"Standing":1,"Behind":2,"Anal":31}},"kyna":{"avirgin":1,"virgin":1,"rel":"6","flags":{"Met":2},"sex":{}},"jeanne":{"flags":{"Met":1,"bg":1}},"golem":{"flags":{"Met":3}},"orchid":{"flags":{}},"raven":{"flags":{"Stage":701}},"party":{"members":["player","kiakai","terry","layla"],"reserve":[],"saved":[],"coin":27339,"loc":"NomadsTent","inv":[{"it":"dildo6","num":8},{"it":"avian0","num":8},{"it":"dog3","num":8},{"it":"demon2","num":8},{"it":"bov0","num":2},{"it":"dildo4","num":8},{"it":"quest0","num":3},{"it":"strapon3","num":8},{"it":"dildo9","num":8},{"it":"dog0","num":8},{"it":"dog1","num":25},{"it":"lago2","num":139},{"it":"felin3","num":161},{"it":"dildo8","num":3},{"it":"dildo8","num":3},{"it":"dildo8","num":1},{"it":"dildo8","num":1},{"it":"dildo8","num":6},{"it":"dildo8","num":1},{"it":"strapon4","num":7},{"it":"demon1","num":8},{"it":"demon3","num":8},{"it":"bov2","num":7},{"it":"dag0","num":4},{"it":"decoy0","num":7},{"it":"dog2","num":8},{"it":"equin3","num":141},{"it":"strapon2","num":7},{"it":"equin0","num":22},{"it":"equin+","num":8},{"it":"sex3","num":8},{"it":"wolf2","num":18},{"it":"avian1","num":8},{"it":"felin0","num":27},{"it":"sex1","num":7},{"it":"fox2","num":10},{"it":"fox3","num":29},{"it":"avian3","num":50},{"it":"goat1","num":25},{"it":"quest2","num":3},{"it":"bov3","num":25},{"it":"felin2","num":153},{"it":"human0","num":13},{"it":"equin1","num":129},{"it":"equin2","num":134},{"it":"human1","num":62},{"it":"demon0","num":8},{"it":"demon+","num":8},{"it":"dildo7","num":8},{"it":"dildo5","num":8},{"it":"rept3","num":50},{"it":"rept2","num":55},{"it":"whip0","num":1},{"it":"rept0","num":17},{"it":"dildo2","num":8},{"it":"strapon1","num":8},{"it":"moth0","num":13},{"it":"lago0","num":27},{"it":"human3","num":62},{"it":"lago3","num":171},{"it":"wolf0","num":11},{"it":"moth1","num":46},{"it":"moth2","num":43},{"it":"dildo1","num":8},{"it":"bov1","num":23},{"it":"naga0","num":7},{"it":"rept1","num":57},{"it":"ovis0","num":8},{"it":"strapon0","num":8},{"it":"lago1","num":163},{"it":"ovis2","num":8},{"it":"quest1","num":3},{"it":"scorp3","num":56},{"it":"rept4","num":14},{"it":"ovis1","num":24},{"it":"robe0","num":2},{"it":"rept5","num":10},{"it":"swrd0","num":15},{"it":"scorp2","num":48},{"it":"quest3","num":1},{"it":"scorp0","num":14},{"it":"dildo0","num":8},{"it":"human2","num":56},{"it":"staff0","num":2},{"it":"scorp1","num":52},{"it":"taur0","num":6},{"it":"sex2","num":9},{"it":"dildo3","num":8},{"it":"felin+0","num":8},{"it":"avian2","num":8},{"it":"sex0","num":2},{"it":"fox0","num":7},{"it":"felin1","num":162},{"it":"wolf3","num":18},{"it":"dildo8","num":1}]},"name":"Tracii(H), Lvl 26/8, 9th of Autumn, year 892","ophelia":{"rel":"76","flags":{"Talk":15,"rotRExp":3,"rotRSex":2},"Btime":{}},"vena":{"flags":{"Met":2}},"roa":{"rel":"50","flags":{"Met":2,"Lagon":2,"snug":1},"sex":{"rAnal":13,"gVag":1}},"oasis":{"flags":{"shop":106947,"Rakh":1}},"patches":{"body":{"vag":[{"cap":"5.00","str":"1.00","wet":"1.00","virgin":1}],"ass":{"cap":"4.00","str":"1.00","virgin":1}},"flags":{"Met":2},"sex":{}},"cveta":{"virgin":1,"avirgin":1,"Vtime":{},"Ftime":{},"rel":"70","flags":{"Met":5,"Herself":3,"Music":1,"Wings":1}},"outlaws":{"flags":{},"rep":"1"},"aquilius":{"flags":{}},"layla":{"body":{"vag":[{"cap":"5.00","str":"1.00","wet":"1.00","virgin":0}],"ass":{"cap":"4.00","str":"1.00","virgin":1}},"flags":{"Met":5,"Skin":1,"Talk":1},"preg":{"gr":"1.00","f":"0.30"},"sex":{"gAnal":10,"rVag":1},"name":"Layla","exp":"65","points":"0","exp2lvl":"124","lvl":"24","sexp":"15","sxp2lvl":"60","slvl":"2","alvl":"0","curHp":"1345.0","maxHp":"100.0","curSp":"1272.0","maxSp":"60.0","curLust":"175.1","maxLust":"80.0","str":"20.0","sta":"22.0","dex":"30.0","inte":"30.0","spi":"35.0","lib":"30.0","cha":"25.0","maxHpG":"10.0","maxSpG":"5.0","maxLustG":"5.0","strG":"1.8","staG":"2.3","dexG":"2.8","inteG":"2.2","spiG":"2.6","libG":"2.4","chaG":"1.9","effects":[],"jobs":{"Fighter":{"lvl":3},"Scholar":{"lvl":3},"Courtesan":{"lvl":6,"exp":185}},"curJob":"Courtesan","ft":{}}} 



     On Sunday, 29 March 2015, 20:12, John Wrenn <notifications@github.com> wrote:
   

 Are you running the compile script and then opening the foe.html file in the build folder afterwards? Might make a difference?—

**Comment by aldergames** [comment]
Thanks, it did. Found the bug. The barbed, sheathed and knotted were coming from your equipped strapon, which was being incorrectly accounted for.

**Comment by Akhter13** [comment]
glad to be of assistance 


     On Sunday, 29 March 2015, 21:29, aldergames <notifications@github.com> wrote:
   

 Thanks, it did. Found the bug. The barbed, sheathed and knotted were coming from your equipped strapon, which was being incorrectly accounted for.—
