### ISSUE TITLE
The game glitches whenever I kill anything, and I can't do anything else.

### ISSUE THREAD

**Issue by tirakai** [AlderArts/foe#229]
Whenever I kill an enemy their image gets a bit cut off and all the buttons disappear, preventing me from doing anything else. This only seems to happen with Chrome, using IE or Opera is fine.
I'm just using my normal PC. Here's a pic of what happens:
![glitch](https://cloud.githubusercontent.com/assets/11810737/6999019/9a43e9d2-dbee-11e4-8cc3-bf12d23f91c3.png)

**Comment by aldergames** [comment]
Check which version of Chrome you're running. This is a known bug in older versions, but should be fixed if you update.
