### ISSUE TITLE
Alchemy improvements

### ISSUE THREAD

**Issue by Kitteh6660** [AlderArts/foe#232]
I think alchemy could use improvements and here are two ways.

**Issue 1:** There's no way of telling if a button will unlock alchemy recipe. The possible proposal is to have the button be green if selecting that button unlocks recipe. It would save having to go back and forth between menus to find a recipe you haven't unlocked, especially when there's one recipe left.
**Issue 2:** The alchemy menu isn't sorted alphabetically. This makes navigation a bit harder especially in the future when you have multiple pages of recipes.

**Comment by aldergames** [comment]
Both should be rather easy to do. It's not 100% certain that you always learn the recipe tho (with Rosalin you do, with Jeanne you don't atm).

**Comment by aldergames** [comment]
Sort was easy enough at least... things sure got easier after I included lodash in the project. Dem neat utility functions.

**Comment by PowerOfVoid** [comment]
![alchemy](https://cloud.githubusercontent.com/assets/3876355/7666771/9c2acca8-fbbe-11e4-8126-a426dc9cdcf3.png)

**Comment by PowerOfVoid** [comment]
Hmm... the interface count might want to retain listing how many you have as well as how many are required.

Especially if the number required is always "1"

**Comment by PowerOfVoid** [comment]
I made the concept art look somewhat prettier:

Assuming all alchemy is one of each input to get one of each output: (You could just list an ingredient multiple times, but that might be confusing)

![alchemy 3](https://cloud.githubusercontent.com/assets/3876355/7755036/458fc39e-ffbf-11e4-81b9-005696119f6b.png)

Without that assumption:

![alchemy 4](https://cloud.githubusercontent.com/assets/3876355/7755098/b4ae8800-ffbf-11e4-8c16-fb6593345684.png)

**Comment by PowerOfVoid** [comment]
This issue is a parent of: #299

**Comment by aldergames** [comment]
I'll call this one done.
