### ISSUE TITLE
Missing "&" in bulltower.js

### ISSUE THREAD

**Issue by kingpingpong** [AlderArts/foe#233]
Line 43 in bulltower.js is missing the second "&" symbol when you are setting what the parse should say. Unless JavaScript does/allows that, although I have only ever seen "&&" in your code.

**Comment by aldergames** [comment]
This is not a bug. The & operator is the "bitwise and", and can be used to single out values from a bitmask. http://en.wikipedia.org/wiki/Bitwise_operation
