### ISSUE TITLE
KiaKai butt capacity and "Ruin" wierdness

### ISSUE THREAD

**Issue by JoBiden** [AlderArts/foe#234]
Currently, the only way to increase KiaKai's butt capacity with the "Ruin" scene. Unfortunately, accessing the "Ruin" scene is tied strictly to KiaKai's anal xp, and not at all to butt capacity. What this means is that doing any non-ruin scene that adds analxp essentially reduces the maximum capacity s/he can reach. I think it would be better to tie access to the ruin scene to a difference between player cock size and KiaKai butt capacity, up to a(n un)natural maximum capacity, which makes more sense for a player intuitively.

Also of note is that it is difficult/impossible to reduce KiaKai's subDom to -100, since the only scenes that can do so only reduces by 3 and 5, and are both one shots, with the next best scenes only reducing to -75. this is currently not too important, since scene variations only require below -60 at lowest, but the only two scenes that reduce to -75 are "Ruin" and "Anal Catch", which when compounded with the "Ruin" restrictions makes it nearly impossible for characters who wish to preserve their anal virginity to reduce KiaKai's subDom below -50. I managed to do so only with extensive cross referencing to the source code. Most scenes only require a -50 to get all variation, except one: the pesky "Ruin" scene has a variation for not being >-60. 

Just generally speaking, manipulating KiaKai's stats to a preferred state is very hard to do naturally, i.e. without referencing the source code or using the elf smith, making a very nice scene variation difficult/impossible to see in game. Im sure these aren't the only examples, but they're the two I ran into while trying to make my perfect subby Kia.

**Comment by aldergames** [comment]
This one should alleviate the problem a bit... the ruin dep on anal exp was inverted, so now you should be able to use it indefinitely. Also looked through the actual capacity checks... things have been a bit messy since I tweaked the system to use thickness instead of length.
