### ISSUE TITLE
Cat tails not Prehensile [intended?]

### ISSUE THREAD

**Issue by JoBiden** [AlderArts/foe#235]
Cat tails aren't considered prehensile, but most people would consider a cats tail to be usable for sex. While not strictly prehensile, it appears like the prehensile flag is mostly being used as a "can fill a hole" flag. Cat tails are also currently described as "flexible", which to me seems to imply some sort of usability/control.

**Comment by aldergames** [comment]
Most scenes that use the prehensile flags use it for penetration I think, so "soft" tails wouldn't work. Function name may be a bit misleading.
