### ISSUE TITLE
Terry Slut score only increasable through horse TF

### ISSUE THREAD

**Issue by JoBiden** [AlderArts/foe#236]
The only way to increase Terry's slut stat currently is by doing horse TF, gentle, for an increase of 1, making most of her slut scene variations impossible to see. Technically the horse TF can be repeated, but at the cost of materials, 250 gold, and no actual TF occurring, its not really worth it.

**Comment by aldergames** [comment]
It's not. Do a code search for "terry.slut.Inc", there's a lot of places that does it.

**Comment by JoBiden** [comment]
hmm. performing such a search pulls up 3 directories on my screen, none of which contain "terry.slut.inc", only terry, slut, and inc in separate areas. When i made this report, i was searching for "terry.slut.increasestat", and only terry-tf had the full string. Maybe its just that we're looking at different things?

**Comment by aldergames** [comment]
There should be plenty of refs for it in terry-sex
