### ISSUE TITLE
Terry suggestions/typos

### ISSUE THREAD

**Issue by CalmKhaos** [AlderArts/foe#238]
This list a bit longer than the previous entry.

With practiced motions, Terry begins stripping her bronze chest, each motion a flourish that emphasises her assets. You watch the delicate vixen’s strip-tease enraptured, drinking in every detail on her lithe body, until she is completely naked. *(Emphasises > Emphasizes)*

“If you got time to be cheeky, you also have time for foreplay. So why haven’t you started yet? And why are you still dressed?” *(comma addition? > So, why haven’t you started yet and why are you still dressed?) – Not sure about the removal of one of the ‘?’. Thought to add a second comma, but wasn’t sure of its flow.*

One eye focused on the naked vixen before you, you make short work of your own stylized clothes, stripping away your clothes until you’re standing before her equally naked. Your own erect big ferret girl-cock stands proudly before you, signalling your readiness to begin whenever Terry gives the okay. *(depending on choice of clothing - like the example of stylized clothes, perhaps change the ‘stripping away your clothes’ to ‘stripping away your attire’?) (Also signalling > signaling)*

Softly, at first, a tender press of flesh on flesh. But as your ardor builds, you kiss the vixen harder, more insistently, sliding closer and closer to her so you can try and dominate her mouth. *(restructure? > Softly, at first, a tender press of flesh on flesh. As your ardor builds, you kiss the vixen harder)*

The vixen regards you with a pour, before sighing. “I can’t really stay mad at you...” *(I would guess ‘pour’ is meant to be ‘pout’?)*

A much bigger idiot than your clever vixen, you immediately reply, chest swelling with pride at her response.
“You got it! Now what did you have in store for little old me?” *(comma addition? > “You got it! Now, what did you have in store for little old me?”)*

You pretend to examine it with great scrutiny before admitting you just want some quality time together. Plus you gotta help your vixen maintain herself. *(comma addition? > Plus, you gotta help your vixen maintain herself.) – Only a small suggestion, maybe change ‘gotta’ to ‘must or have to’ for grammar sake. Totally understand if you want to keep it the way it is.*

“As good an excuse as any. You know where I keep my comb and my brush right?” *(comma addition?/phrase structure > “Well/Well, that’s as good an excuse as any. You know where I keep my comb and my brush, right?”) – Again, only a small suggestion for the phrase.*

You find Terry’s pack and rummage through it. At first you just find a few spare clothes, panties, few tools of the trade, and a couple dry snacks. But once you get to the bottom you raise a brow at what you see. A dildo, lube, a cockring, another dildo, an inflatable buttplug, more lube, and some honey. Chuckling to yourself you ask whyever she would need all of that? Doesn’t it get heavy having to lug around all these toys? *(Hmm… perhaps some restructuring/punctuation changes? > You find Terry’s pack and rummage through it. At first, you just find a few spare clothes, panties, few tools of the trade and a couple dry snacks. Once you get to the bottom, you raise a brow at what you see. A dildo, some lube, a cock ring, another dildo, an inflatable butt plug, some more lube and some honey. Chuckling to yourself, you ask why ever would she need all of that? Doesn’t it get heavy hauling around all these toys?)*

“Gotta be prepared for when you’re not around, my dear mistress. Plus in case you’re feeling kinky in the middle of the forest, I’d rather not have to wait until we find a city to go after the big girl toys,” she grins innocently. *(comma addition?/perhaps grammar clean-up? > “Have to be prepared for when you’re not around, my dear [mastermistress]. Plus, in case you’re feeling kinky in the middle of the forest, I’d rather not have to wait until we find a city to go after the big girl toys,”)*

“Maybe you did, but I loved every second of it. And so did you.” *(perhaps use an addition comma instead of period? > “Maybe you did, but I loved every second of it, and so did you.”*

True. In that case you’ll just have to enjoy the spoils of your hard labor. *(comma addition? > True. In that case, you’ll just have to enjoy the spoils of your hard labor.)*

After digging through quite a few toys, you finally manage to secure Terry’s comb and brush. Carefully you put away everything back into her pack and move to the grinning vixen. *(comma addition?/small restructure? > Carefully, you return everything back into her pack and move to the grinning vixen.)*

You circle her until you’re behind her, then remove the small strap holding her pony tail. Terry doesn’t look half-bad with her bangs loose… Well, plenty of time to admire later; first of all you decide to begin with the comb. As neat as the vixen is, her hair is perfectly cared for and provides minimal resistance as you rake the comb through her locks. Then you set down the comb and grab the brush. *(some punctuation changes?/some restructuring? > You circle her until you’re behind her. You remove the small strap holding her ponytail. Terry doesn’t look half-bad with her bangs loose… Well, plenty of time to admire later; first of all, you decide to begin with the comb. As neat as the vixen is, her hair is perfectly care for and provides minimal resistance as you rake the comb through her locks. You set down the comb and grab the brush.)*

**Comment by aldergames** [comment]
Terry is a bit taken by surprise initially, but she quickly reciprocates, tail wagging slowly behind as her eyes close. Her tongue wrestles with yours, and she moans a little as you twist your heads slightly to deepen the kiss. (Maybe change ‘bit’ to ‘little’?)

- You miss the "she moans a little" in the next sentence.

**Comment by CalmKhaos** [comment]
Ah, I see. I sure did overlook that.

**Comment by aldergames** [comment]
Test *test* **test**
Use stars (*) around stuff to bold/italics the actual change.

**Comment by CalmKhaos** [comment]
Thank you for the (*) suggestion. I'll remember to use that from now on.

**Comment by aldergames** [comment]
** would be even better (bold)
