### ISSUE TITLE
More Terry typos/suggestions

### ISSUE THREAD

**Issue by CalmKhaos** [AlderArts/foe#239]
Some more suggestions/typos, all at your discretion of course.

“My tail, huh? Pretty sure you have other intentions. And if you don’t, then I’m pretty sure you’ll have them by the time you’re done. But okay, I’ll play along then, just try not to be too obvious about it,” the vixen says, grinning mischievously. **(comma addition? > Pretty sure you have other intentions, and if you don’t, then I’m pretty sure you’ll have them by the time you’re done.)**

 “Hey, those clothes would only get in the way. Plus I was hoping to convince you to brush the rest of my fur too. Especially since you seem so fond of making it messy,” she chuckles. **(comma addition?> Plus, I was hoping to convince you to brush the rest of my fur too.)**

“Yeah, If I let it get too messy then it becomes pretty hard to move it around. And it also hurts. Plus keeping it neat makes it better for drawing the eyes of a certain someone,” she adds, with a smile, wagging her tail a bit. **(some punctuation?> “Yeah. If I let it get too messy, then it becomes pretty hard to move it around, and it also hurts. Plus, keeping it neat makes it better for drawing the eyes of a certain someone,”)**

You gaze flicks to Terry’s head, and you can’t help a smile of amusement at the way her ears are daintily flicking in her half sleeping state. They’re just too cute; you really want to pet them... **(small change?> Your gaze flicks to Terry’s head and you can’t help but put on a smile of amusement at the way her ears are daintily flicking in her half sleeping state.)**

For now you decide to ignore Terry’s lame excuse and focus on your ministrations. Your whole palm now overlays itself on Terry’s head, stroking back and forth, tussling her ears from side to side. **(comma addition?> For now, you decide to ignore Terry’s lame excuse and focus on your ministrations.)**

You smile back, assuring her that you’d be happy to give her a hand whenever she feels like it. But, for now, you both have other things to do. Terry sighs and vacates your lap, whilst you get back to your feet and head off again. **(small change?> You smile back, assuring her that you’d be happy to give her a hand whenever she feels like it, but for now, you both have other things to do.)**

Quietly, you continue to brush the vixen’s sleek, clean tail-fur, running the prongs of your brush through her tail in companionable silence. The two of you remain there for several pleasant moments, just feeling each other’s body next to you, before you put the brush aside and announce that you’re finished. **(maybe change ‘your brush’ to ‘the brush’ – considering the PC is using Terry’s brush. Would that change work with the second ‘the brush’ segment?)** **(small change?> The two of you remain there for several pleasant moments, just feeling each other’s body, before you put the brush aside and announce that you’re finished.)**

“Alright then, you got me. I’m in no position to fight back. So I guess I’m at your mercy,” she says with a grin. **(comma replace? > I’m in no position to fight back, so I guess I’m at your mercy,”)**

“Wha? Hey cut it out!” Terry exclaims, batting your hand with her tail. “Don’t tease my birthmark, you perv!” **(comma addition? > “Wha? Hey, cut it out!” Terry exclaims, batting your hand with her tail.)**

“W-Well… Just don’t tease my birthmark. You know how embarrassed that makes me...” **(small change?> “W-Well…, just don’t tease my birthmark.)**

But, if that’s the way she wants it, you’ll leave it alone. For now. She’s kind of cute when she gets all upset like this... **(small change?> If that’s the way she wants it, you’ll leave it alone – for now.)**

A scent tickles at your nostrils and you sniff, trying to figure out what it is. After a few moments, you recognize it as the distinctive scent of female arousal - and it’s coming from between Terry’s legs. No matter how she squeezes her thighs together to try and hide it. With a grin, your hand snakes down, worming its way between the vixen’s clenched thighs to try and touch the dampness of her cunt. **(small change?> After a few moments, you recognize it as the distinctive scent of female arousal – and it’s coming from between Terry’s legs, no matter how she squeezes her thighs together to try and hide it.)**

Some other time, you might be interested in seeing. But, right now, you don’t feel that way. Instead, you carefully pop your finger free from the sucking embrace of Terry’s tailhole, giving her a conciliatory pat on the butt with that hand. You continue stroking for a few moments, before you slowly put your brush away and cheerfully announce Terry’s good to go. **(small change? > Some other time, you might be interested in seeing but right now, you don’t feel that way.)** **(You continue stroking for a few moments, before you slowly put the brush away and cheerfully announce Terry’s good to go.)**

Smiling, you reach out and playfully tussle the vixen’s ears with your fingertips. And what’s wrong with her being a little excited. You quite like how she looks like that. **(small change? > Smiling, you reach out and playfully tussle the vixen’s ears with your fingertips. What’s wrong with her being a little excited?”)**

Ha! And she calls you a perv. Well, you did just want to touch that fluffy tail of hers, getting her all worked up was just a bonus. And considering how cute she looks when she pleads like that, you think you’re going to make her wait for it. At least for a little while. **(small change?> Well, you did just want to touch that fluffy tail of hers, getting her all worked up was just a bonus. Considering how cute she looks when she pleads like that, you think you’re going to make her wait for it – at least for a little while.)**

If she’s a good girl, you promise to help her with that. For now tho, she should get dressed. **(tho > though)**

Sighing, Terry conceded. “Fiiiine. I guess there’s no arguing with you...” **(maybe concedes instead of conceded?)**

“My, my, someone can’t get enough of my butt.” She grins. “Alright then, you can have it. But you’ll have to come and get it.” The vixen winks. **(small change? > “Alright then, you can have it, but you’ll have to come and get it.”)**

Well, that’s an invitation you can hardly refuse. In a few brisk motions you have crossed the distance between the pair of you, one hand moving to possessively cup Terry’s ass. **(comma addition?> In a few brisk motions, you have crossed the distance between the pair of you, one hand moving to possessively cup Terry’s ass.)**

With your thumb, you continue spiralling around and around Terry’s tailhole, until you deem the surface sufficiently lubed. Now it’s time to start lubing her up inside... **(spiralling > spiraling)****(comma addition?> Now, it’s time to start lubing her up inside…)**

Patiently you pump away with your finger, feeling Terry stretching around the intruder. **(comma addition?> Patiently, you pump away with your finger, feeling Terry stretching around the intruder.)**

You reach for Terry’s new womanhood, already starting to plush with arousal. Gently you stroke her feminine sex, slowly running your fingers through the folds, feeling her excitement beginning to bead on your fingertips and run down to puddle in your palm. **(comma addition?> Gently, you stroke her feminine sex, slowly running your fingers through the folds, feeling her excitement begging to bead on your fingertips and run down to puddle in your palm.)**

As the moments tick past, you feel Terry’s ass slowly growing looser, slackening its grip around your big ferret clit-cock as the vixen recovers from your initial penetration and relaxes. **(small change?> As the moments tick past, you feel Terry’s ass slowly growing more loose, slackening its grip around your [cock] as the vixen recovers from your initial penetration and relaxes.)**

Terry groans as your hips connect with her ass, instinctively clenching as you begin to pull out, then relaxing when you push back in. Without realising the two of you have fallen into a brisk, but steady pace. “Hng! H-Harder,” the vixen begs, lust-addled eyes glancing at you over her shoulder. **(comma addition?> Without realising it, the two of you have fallen into a brisk, yet steady pace.)**

“You know, Ky. Any other time and I’d tell you I love you, but right now I freaking hate you. Ow, my ass...” **(small change?> “You know, [playername]… Any other time, I’d tell you I love you but right now, I freaking hate you. Ow, my ass…”)**

“Hardy, har, har. Ain’t you lucky that you found someone that likes you, despite your lame one-liners, and weird antics?” she asks mockingly. **(comma removal?> Ain’t you lucky that you found someone that likes you, despite your lame one-liners and weird antics?)**

For emphasis you catch Terry’s tail near its base in your hand, gently stroking down its length. **(comma addition?> For emphasis, you catch Terry’s tail near its base in your hand, gently stroking down its length.)**

Gently you part Terry’s asscheeks, the white fur giving way to the naked pink flesh of her anus. **(comma addition?> Gently, you part Terry’s ass cheeks, the white fur giving way to the naked pink flesh of her anus.)**

Patiently you squirm and pry and poke, slowly teasing it open and feeding your tongue inside, worming it deeper and deeper until you are buried in her ass. **(comma addition?> Patiently, you squirm and pry and poke, slowly teasing it open and feeding your tongue inside)**

Patiently you feed inch after inch of your length inside of her, trying to make the insertion as gentle as possible. **(comma addition?> Patiently, you feed inch after inch of your length inside of her, trying to make the insertion as gentle as possible.)**

“Thanks for making me cum so hard, Ky. But surely we’re not finished yet, are we? You didn’t cum. And you can’t just hold out on me like this. If you don’t give me treats I might grow rebellious,” she smirks mischievously. It’s clear that she’s tired, but you can also tell that she’s not about to collapse without at least getting you off. **(small change?> “Thanks for making me cum so hard, [playername], but surely we’re not finished yet, are we? You didn’t cum, and you can’t just hold out on me like this. If you don’t give me treats, I might grow rebellious,”)**

“It’s a promise, make sure to have plenty of cum backed up for me later. But for now, can we snuggle? I can’t sleep very well without my Ky.” **(small change?> “It’s a promise. Make sure to have plenty of cum backed up for me later, but for now, can we snuggle? I can’t sleep very well without my [playername].”)**

“Okay then, back to the beginning. I suppose...” **(small change?> “Okay then. Back to the beginning, I suppose…”)**

“My father tells me that when he heard the news he was surprisingly joyous. He and mom never married, but they started living together all the same. Who said someone needs to be married to have a family together?” **(comma addition?> “My father told me that when he heard the news, he was surprisingly joyous. He and mom never married, but they started living together all the same. Who said someone needs to be married to have a family together?”)**

“To be honest I don’t remember my mother that well. I was just a baby when she died. Some trouble with morphs here in Rigard. I don’t recall the exact details. But you can see that the bigotry still runs strong.” Terry sighs. **(comma addition?> “To be honest, I don’t remember my mother that well. I was just a baby when she died. Some trouble with morphs here in Rigard… I don’t recall the exact details, but you can see that bigotry still runs strong.” Terry sighs.)**

“Alright then. Now where was I...” **(comma addition?> “Alright then. Now, where was I…”)**

“My dad was surprisingly caring when it came down to raising me. Although he did have some bad habits.” **(small change?> “My dad was surprisingly caring when it came down to raising, although he did have some bad habits.”)**

“Yeah, well. I look pretty girly to begin with. And booze kinda blurs things. He never touched me, just kept saying stuff to me. It was kinda sad. I could tell that he really loved mom. I never bothered correcting him either. Sometimes I’d just pretend to be a woman and reply in kind.” **(small change?> “Yeah. Well, I look pretty girly to begin with and booze kinda blurs things. He never touched me, just kept saying stuff to me. It was kinda sad. I could tell that he really loved mom. I never bothered correcting him either. Sometimes, I’d just pretend to be a woman and reply in kind.”)**

“So, when he was sober enough, he thought he’d train me. Said it always paid to know a thing or two about the ‘finer arts’, his words. And it turns out I was pretty good at it too. Of course, the fact that I looked pretty darn innocent and meek also helped my cause.” **(small change?> “Whenever he was sober enough, he thought he’d train me. Said it always paid to know a thing or two about the ‘finer arts’, his words – and it turns out I was pretty good at it too. Of course, the fact that I looked pretty darn innocent and meek also helped my cause.”)**

“Father worked at the docks. Loading and unloading ships, and if something went missing? No skin off his back. I mean, things go missing all the time during the busy hours. Pretty sure my dad wasn’t the only one relieving a few of the dirty rich merchant of some of their precious cargo.” **(small change?> “Father worked at the docks, loading and unloading ships, and if something went missing? No skin off his back. I mean, things go missing all the time during the busy hours. Pretty sure my dad wasn’t the only one relieving a few of the dirty rich merchants of some of their precious cargo.”)**

“Those were good days. But they only lasted a couple years. Dad… well, he didn’t last long.” Terry’s visage saddens for a moment. **(small change?> “Those were the good days, but they only lasted a couple of years. Dad… well, he didn’t last long.” Terry’s visage saddens for a moment.)**

**Comment by aldergames** [comment]
Would be even more helpful if the actual changes (rather than the entire section) was highlighted some way

**Comment by CalmKhaos** [comment]
Sorry about that. I thought to do it that way to keep track of the section I was working with and to attempt to limit any past errors like the 'bit, little' segment from an earlier suggestion. I'll highlight only the actual changes from now on.

**Comment by aldergames** [comment]
Appreciated. Even if I just copy-pasted (which I can't, due to the parser. All the "she"s are [heshe] in code for example), I still need to evaluate *what* the change actually is first.

**Comment by CalmKhaos** [comment]
Ok, I think I understand what you are saying for highlighting changes. If it's ok with you, I'll try to provide a change here for your review.

***Anyways,*** I was all alone and I had to fend for myself. Daddy’s skills came in pretty handy***, but*** I was pretty scrawny by comparison. ***Working*** at the docks? No dice.” She shakes her head.

Is this suitable?

**Comment by aldergames** [comment]
Yup, that works

**Comment by CalmKhaos** [comment]
Ok, good. I'll continue to use this format for any more suggestions I may find. Thanks for the help.
