### ISSUE TITLE
Even more Terry suggestions/typos

### ISSUE THREAD

**Issue by CalmKhaos** [AlderArts/foe#240]
Without reading the actual scripts themselves, these are most of the interactions I have available to freely look over. For your review and discretion as always. Hopefully, this will be easier to read for you.

“***Instead,*** I managed to land a job at the local inn. It wasn’t as safe as the docks, but at least I could pick my marks ***and*** my fingers were light enough that few even noticed missing goods. I didn’t steal anything major, after all.” A smile breaks on her muzzle.
 
“I was pretty naive back then ***- also*** pretty darn careless.

***Initially,*** that was my motivation. But as time passed and he trained me, I grew to like him. That, however, is a tale for another time. Maybe later?

Can’t say I loved wearing a few of those frilly dresses ***though***...

You can’t believe the things people will babble about to a pretty face and some giggles. ***I played the part well - with*** me looking all girly and everything...

Not that I resent him for that. It was all in good fun***, though*** there was a time when I kicked him in the nuts for a particularly offensive remark.”
 
“Yeah, he kinda did. We had a good run, but ***eventually,*** I guess he was too cocky and things didn’t end up well for him. But let’s visit that some other time, alright?” 

“***About then,*** we caught wind of a VIP that was visiting the town we were in. Thorn’s eyes were aglow. That was a great mark if there ever was one ***and*** best of all? He had little security with him. It was an opportunity ***and*** if there’s a thing you learn in thievery, it’s that you never miss an opportunity.”
 
“***Our mark was Duke Kane.*** ***He*** was responsible for the neighbouring town and had vast ***amounts*** of land under his name. **{*the change ‘vast amount of land’ to ‘vast amounts of land’ – going by how the sentence is worded, although could use ‘had a vast amount of land’ if that was the intent*}**

“No, he didn’t stay anywhere near me. I was simply a maid at the local inn***, but*** I did get the chance to speak with a few guards. ***Naturally, I*** had to deflect more flirts than I’d like,” Terry adds, cringing at the memory. 

I wanted to get away from it all, plus there was always the chance people would find out I was with Thorn ***and then*** I’d be in trouble too. 

It was a long trip, but ***eventually,*** we made our way to Rigard. 

Did ***he*** recall it at all from her childhood? **(looks to have an issue with identity on the second sentence… Did ‘she’ recall it at all from her childhood?)**

Even long after ***the*** conflict that took my mother from me, people were still on edge. ***Finding*** a mark was tough. ***In the end,*** I decided if I wanted to score some decent loot, I’d have to rob one of the local nobles.” 

***With a*** studious look on your face, you start to circle Terry, intensely observing her from all angles, gaze moving up and down, back and forth ***as*** you continue to trail around the puzzled vulpine. 

***Now,*** that’s what you were waiting for. Warm wetness creeps slowly over your sensitive flesh ***, even*** as tingles race along your spine.

You find yourself unconsciously bucking your hips, the vixen‘s muzzle feels so good that you just can’t resist it ***- at least this helps you regain a little bit of control.***
**(It looks like these sentences should be together instead of being separated for continuity sake, maybe?)**

It’s hard for you to admit it, ***but right now,*** Terry is playing you like a master plays a fine-tuned instrument.

Rather than fighting to gulp down your load, she resolves to simply hold her throat open and let your big clit-cock pour ***your*** seed straight down her gullet.

“***Now,*** be a good girl and spread ‘em for me.

You settle on the ground and spread your legs to give Terry easy access to your very flexible crevice***, adjusting your legs to ensure that Terry has no problems.*** **(I’ll admit: I couldn’t think of anything suitable to replace the repeated statement that would ‘fit’ better, in a sense – Perhaps you might be able to?)**

Terry’s touch is feather-soft, almost too light to feel at times ***and yet,*** she manages to leave ripples of pleasure in her wake.

*If I had a* ***cock,*** *I might just give up on licking you and fuck you instead*

***Vigorously, you continue thrusting***, feeling yourself climbing the metaphorical wall.

Terry is only capable of crying out in pleasure, as cum gathers in her once-soft fur***, utterly*** plastering it with the results of your recent activities.

You push your big clit-cock below the vixen, letting *them* emerge from behind her. ***(them is being used for one cock instead of it)***

All in due time, you quip back. First of all, you think some foreplay is in order***- just to get her started.***

***Carefully,*** you glide over the cum-caked fur, heavy enough to lap the off-white smears from its surface but not enough to coat your tongue in fur.

***Painstakingly,*** you wash your way up Terry’s belly, pausing at its peak to worm your way into her bellybutton, wriggling in circles along the indent’s walls, tongue pumping playfully in and out.

***Slowly,*** you slide your tongue over your lips, swallowing heavily as your eyes sink half-closed with pleasure.

***By this point,*** Terry is reduced to a moaning mess, but she still does her best to reciprocate your thrusts. “I - Ah! - I don’t know what brought this ***on, b-but I like it!***”

No sooner have your hips battered against Terry’s ***rear, you explode inside of her***, hot seed gushing freely into her hole.

Terry’s belly begins to bloat, swelling into a ***cantaloupe***-sized bulge

***Finally, your*** climax ends and you slump over Terry’s prone form, panting from the exertion.
Didn’t know you’d get this ***turned on*** penetrating me **(maybe I’m missing it, but ‘turned over’ sounded a little strange to me – Is it, perhaps, based on an older definition?)**

“***Not that I’m complaining***, but wow… what brought this on?” **(or Now, not that I’m complaining)**

“I see.” Terry takes a deep breath and smiles. “Well, if you really want that, I have no objections, though I expect to be pampered and spoiled if it took,” ***she adds teasingly.***

***For a moment,*** she loses her composure and just pants in lust, but she quickly recovers and goes back to licking and suckling on your tip.

You smile as you feed more of your tail inside of the vixen’s ***pussy.*** ***Without*** being able to see, it’s a little trickier, as your tail isn’t as sensitive as your cock, but you soon feel content to start pumping away with your appendage.

***As some*** of it winds up escaping the sides of her muzzle, she doesn’t stop. **(maybe Even though some?)**

***However,*** as your big girl-cock springs free, a leftover strand shoots out to plaster itself across the vixen’s muzzle.

The vixen’s eyes dart toward you ***and as your gaze meets hers***, she smiles.

Terry adjusts her hair a bit and straightens her posture as she stretches languidly, giving you a ***perfect, unobstructed view of herself.***

“Ha! I will if you really want me ***to, but*** you’ll have to go naked yourself. If I’m going to be giving you eye-candy all the time, I expect the same treatment,” she quips back.

The vixen sometimes has cravings, but that’s to be expected of a pregnant vixen ***- at least she’s not feeling sick anymore.***

**Comment by aldergames** [comment]
You settle on the ground and spread your legs to give Terry easy access to your very flexible crevice, adjusting your legs to ensure that Terry has no problems. (I’ll admit: I couldn’t think of anything suitable to replace the repeated statement that would ‘fit’ better, in a sense – Perhaps you might be able to?)

This bit was a logic error, a missing else that accounted for no-legs (naga etc).

**Comment by CalmKhaos** [comment]
Ah, ok then. It just struck me as a 'how could I attempt to provide a suggestion for it' moment. Thank you for the clarification.
