### ISSUE TITLE
Chief.js typos

### ISSUE THREAD

**Issue by theobserver12** [AlderArts/foe#243]
Line 62: <i>“I'm the chief, herding these here folks in about the same direction, looking out for their interests**,** so to speak.”</i>

Line 227: I hung out with the wrong sorts, or so the city watch felt about it, anyway**.**”</i>

**Comment by aldergames** [comment]
And... what are the typos? :P

Some of the dialogue is a bit weird, but chalk it up to accent.

**Comment by theobserver12** [comment]
Comma after interests, period after anyway.

Bolded them, but still kinda hard to see.

**Comment by aldergames** [comment]
Use stars around the text (**)

Example: **bold text**
