### ISSUE TITLE
Some Layla typos/suggestions

### ISSUE THREAD

**Issue by CalmKhaos** [AlderArts/foe#245]
For your review.

Layla is a… ***well,*** you’re not sure what she is exactly, so you’re just calling her a chimera for now.

Of course you can do it ***again, but*** you were hoping for a little more detail on what she thinks of it than that.

She looks at you ***curiously,*** then stops to think about it for a ***moment.*** ***After some time passes…,*** she shrugs. “I love it. And I’d like to learn more about it, but I’m not sure what else to say...”

Layla isn’t wearing any real clothing, and the ***’clothing’*** she appears to wear is nothing but her own skin, shifted to appear as ***such***.

A second such phallus conceals itself within the tip of her long tail, like a lewd version of a ***stinger, although*** much smaller than the first phallus - only six inches long and an inch thick - it is otherwise identical.

All in all, it’s fairly ***reptilian-looking, discounting*** that she has smooth skin as opposed to scales, of course.

You know she can plump it up at ***will – just*** like she can with her breasts, but she’s most comfortable with it as it is.

Layla’s butt is just begging to be ***touched.*** ***Without thinking,*** you reach out and grope one svelte cheek.

For a ***moment,*** you ponder if that was an innocent compliment or if she meant something more by it.

They’re human in shape, slender and shapely like a woman’s ***should be and yet,*** there’s a sense of power to them, of muscle hidden beneath the curves.

Finally, your gaze ends up on Layla’s feet. Like her legs, they’re human at first ***glance, but*** the toes are just slightly... off.

They’re feet designed for ***running and climbing.***

Layla wraps you in a ***hug as*** soon as you are within reach.

Before you can really ***begin, you*** are almost bowled over by a happy, horny chimera.

There’s a confusing cascade of motions as they undulate and squirm, undoing straps, unfastening buttons, opening ties, worming into sleeves, curling into ***and under things…*** **(I guess this was the intended phrase for what’s going on?)**

One of her hands moves between your legs to fondle your balls, testing their ***weight. You*** coo quietly in pleasure, arching your back as Layla’s hands toy with your nethers. **(just to clarify – it was a space needed between ‘weight’ and ‘You’)**

As if taking your posture as ***an*** invitation, the chimera lowers herself atop you.

Something warm and wet glides lovingly along the back of your neck, sending tingles racing across your **skin.** **(Would this still apply if said PC has fur/scales?)**

You moan in bliss; the feeling of your big ferret clit-cock dripping precum and your very flexible box oozing ***nectar onto*** the ground beneath you is simply sublime.

She kisses, ***tongues and thrusts*** with even more passion than before, grinding herself wildly against you.

Your big girl-cock aches and throbs, hard as diamond before erupting ***in geysers*** of semen that washes over your belly, spilling messily down your thighs and puddling on the ground.

A quiver runs along your spine, tingling under your **skin** as the first drops of warm pseudo-pre splash upon your sensitive pucker. **(Would this still apply if said PC has fur/scales?)**

A groan of pleasure wrings itself from your throat as you feel your loose anal opening spreading ***itself*** wide to receive the chimera’s alien cock.

You thrust your ***noticeable*** hips back, anxious to be filled, and do your best to thank Layla by milking her tailcock for all you’re worth. **(an 'e' is missing for notic*e*able)**

No sooner has the thought ***processed, she*** abruptly jerks her cock ***free. She lets*** her last spurts of mock-semen rain down upon your ass, flowing like a waterfall through your buttock-cleavage.

Pleasure sings through your veins, dances under your **skin.** **(Would this still apply if said PC has fur/scales?)**

You open your mouth without ***hesitation and*** immediately Layla’s tail glides inside.

Each buck and thrust of your lover makes a perverse ***squelching, slapping*** sound as she stirs the semen inside of you before slamming against your buttocks.

You sigh softly, a shiver of pleasure running through ***you and*** with her help, you finally get yourself shut fairly tight.

You open your lips, extend your animalistic ***tongue and*** curl it around the tip of Layla’s tail, lazily lapping at it in tantalizing strokes.

You watch in delight as Layla’s tail-tip splits open, fleshy lips peeling back like a blossoming flower to reveal the ***shiny, wet*** shape of her hidden cock.

In this position, all you have to do is focus on sucking ***her as*** she licks your ass and pumps your mouth full of tasty aphrodisiac.

***Soon,*** you’ll have a nice serving of refreshing tail-juice to drink down.

The first jet goes inside her mouth, the second jet hits her on perky ***breasts and*** the rest falls onto her intended ***target – her own cock.***

You moan excitedly, relishing the feeling of Layla suckling at your perky nipple, toying with you using lips, ***tongue and*** even teeth.

Pleasure is washing through your being, ***carrying you*** to the heights of delight. **(This seemed to be a difficult one to make a suggestion for… Trying to find something suitable to replace the original wording and yet, it still doesn’t seem to ‘flow’ in my opinion. Three things come to mind: 1st – carrying you  2nd – raising you  3rd – soaring. I’ll leave it to your decision.)**

**Comment by aldergames** [comment]
There’s a confusing cascade of motions as they undulate and squirm, undoing straps, unfastening buttons, opening ties, worming into sleeves, curling into and under things… (I guess this was the intended phrase for what’s going on?)

I'm thinking underthings as in undergarments and similar.

**Comment by CalmKhaos** [comment]
Since you put it that way, that's a fair point.

**Comment by aldergames** [comment]
Pleasure is washing through your being, carrying you to the heights of delight. 

Think this works?

Pleasure washes through your being, carrying you to soaring heights of delight.

**Comment by CalmKhaos** [comment]
Yeah, that actually sounds better in my opinion.
