### ISSUE TITLE
Some Lusina (moth-girl) typo/suggestions

### ISSUE THREAD

**Issue by CalmKhaos** [AlderArts/foe#246]
For your review. I should take a break on these... >_>

The moth-girl sighs and swings her claymore into a ***defensive stance***, saying “Tsk, you just have to do it the hard way, don't you? Oh, well… ***en garde!***”

You know what you ***want – and*** if she's half as sensitive as she seems, the wanton little moth might even like ***it too.***

As she sucks you off, you let your hands play down her largely lithe, supple frame, slipping down her slender arms to her flat belly, then up again ***to*** her big, bouncing breasts, cupping a full, fleshy orb in either hand. 

***The*** moth-girl seems to enjoy it too, breathing harder as your hips slap wetly against her ***tits. She starts*** moaning louder with every thrust until you feel her hands moving beneath yours, moving her tits to meet your hammering womanly hips, thrusting them back against you to redouble your pleasure and hers.

She gives an almost giddy gasp as a thick pool of pre drools from the slit of your big ferret clit-cock and onto her ***flesh – a*** hot drop of musky ejaculate that draws out a primal lust from the ***moth as*** the next drop lands on the tip of her ***long,*** insectile tongue.

You grit your teeth, trying not to cry out as you feel your big ferret girl-cock swelling with seed, surging toward the ***slutty*** bug.

As a reward, you let your free hand slip up, brushing along the moth's cheek up and toward one of the **tall, floppy purple feelers sprouting from her brow.** **(As for the feelers, wouldn’t that be ‘from the top of her head’ instead?)**

If you thought she was ***whimpering*** before, she redoubles the moment your fingers brush the delicate, silk-like plumes, sending shivers of ecstasy trembling down her buxom body.

Digging your hands into the moth's behind, you grit your teeth and push yourself deep into her tight anal ***passage.*** ***You try*** not to let the overwhelming sensation get the better of you - but it's so hard not to cum right then and there, milked to completion by the thief's writhing muscles. 

A few slow thrusts ***later, she*** manages to relax herself, finally getting used to the feeling of your big girl-cock in her butt.

The more she relaxes, the faster you move, picking up the pace until you're slamming your flared hips in the moth's plush behind, making her ass bounce to the beat of you ***fucking her.***

The thought of a long, lashing tongue writhing inside you sends a shiver of anticipation through your ***body and*** a hot rush of excitement to your sex.

The moth-girl sputters as she's submerged in your juices, lips locking with your ***pussy*** as her tongue is pushed through the tight-clenched slit of your very flexible snatch.

Biting your lip, you spread yourself out with your fingers, easing the **mother's intrusion**; she takes the opportunity to push in hard and fast, wrapping her tongue through to the lips of your womb, grabbing your squeezable tush to pull you in on her. **(maybe I’m not understanding the context of those words, but wouldn’t this just be ‘moth’s intrusion’?)**

You gasp as the moth pulls just a little too ***hard.*** ***Unsteady*** as you are, a little force is all it takes to send you toppling down atop her, rolling with the bug through the grass until the two of you come to a standstill, straddling her big hips. **(a little unsure about the suggestion here)**

You're not far behind ***her as your hips are*** bucking back against her tongue, using it like a thick, writhing cock to get yourself off ***on and*** liberally drenching the moth's face and chest with your flowing juices as you do so.

As her pleasure mounts, it's as if she loses control of her tongue: the muscle goes wild inside you, thrashing ***about*** like a ***fire hose***, fucking its way so deep inside you can feel its tip kissing the entrance of your womb.

**Comment by CalmKhaos** [comment]
If I may add some more (missed these from earlier):

The moth-girl ***clicks*** her tongue as your wandering eyes drinking in the soft mounds of her bare breasts, the stiffening peaks of her pink nipples as they harden under your lustful gaze.

“Like what you see? I have to say, they're **definitely** my best assets, don't you think?” **(By her context, bold/italicize ‘definitely’)**

While you're enthralled by the display, her other hand works its way down to her waist, thumb hooking through her belt and ***letting her pants fall*** down.

With a grin, the moth-girl slips a hand under your stylized clothes to grab one of your big ferret girl-cock, **(If PC only has one cock, wouldn’t it be better to say ‘to grab your’ instead of ‘to grab one of’?)**

You suckle on the moth's tit, tongue lavishing it with ***licks, slurps and*** gentle teases between your teeth as she grinds herself against you, her ragged breath turning to sweet ***moans, little gasps and cries.***

Her movements ***become*** faster, ***breathing*** less and less steady as ***your mouth, fingers and cock*** work their magic on her tender body, working all her sensitive spots until she's a writhing mess of near-orgasmic bug-slut, all but begging for release.

You keep doing what you're doing, ***suckling, fingering and fucking harder and faster*** until the moth throws her head back with an ***orgasmic*** scream of pleasure that echoes out around ***you.*** ***She roars in*** feminine ecstasy as fem-cum gushes out around you, smearing your crotch with her juices as she cums and cums, her orgasm lasting for what seems like a blissful eternity. **(Attempted to give this long sentence some separation. I’m not completely sure if this will work though.)**

**Comment by aldergames** [comment]
With a grin, the moth-girl slips a hand under your stylized clothes to grab one of your big ferret girl-cock, (If PC only has one cock, wouldn’t it be better to say ‘to grab your’ instead of ‘to grab one of’?)

That was the thought, but there was a bug that had crept in.

**Comment by aldergames** [comment]
'orgiastic' - this is an actual word. Not applicable here perhaps, since there are no orgies involved.

**Comment by CalmKhaos** [comment]
Learn something new everyday :P. Thanks for the info.
