### ISSUE TITLE
Bovine cock descriptor

### ISSUE THREAD

**Issue by Stonecolt** [AlderArts/foe#247]
Sometimes bovine cocks are referred to as cow cocks. Cows are generally thought of as female, would there be any way to change that to bull instead.

**Comment by Stonecolt** [comment]
Nevermind, I figured out a fix to my body.js file I can live with. under Race.Desc = function(race) I changed  

case Race.cow: r = Rand(2);
		if(r == 0) return "cow";
		else       return "bovine";

to

case Race.cow: r = Rand(2);
		if(r == 0) return "minotaur";
		else       return "bovine";

That gives me the minotaur descriptor for cocks (and race if that becomes available). Not perfect but more gender neutral at least

**Comment by aldergames** [comment]
Can see the problem, but I can't just set it to bull instead (since it's used for other things too, where male gender wouldn't work).
