### ISSUE TITLE
Chest not showing up in Krawitz Estate?

### ISSUE THREAD

**Issue by hyufuj** [AlderArts/foe#248]
I'm not sure if this is a bug, but:

With a character with int>30, the text delivered by [line 782 in Krawitz.js](https://github.com/AlderArts/foe/blob/6e513f5984c30255476b4de8bf91bbed8999da20/js/loc/rigard/krawitz.js#L780-782) suggests that the chest has been found ("Where could the good stuff be hidden? Scanning the room once more, your eyes hone in on a drapery hanging at the very back of the room. Pulling it aside, you uncover a small ornate chest. Too easy.").

However, [line 820](https://github.com/AlderArts/foe/blob/6e513f5984c30255476b4de8bf91bbed8999da20/js/loc/rigard/krawitz.js#L820) has this check:
`return !Scenes.Krawitz.stat.TFItem && (Scenes.Krawitz.stat.ChestLocKnown || player.Int() > 40)`

I'm not certain if you intend for the player to find the chest or not when they have 30<int<40, but there it is.

**Comment by aldergames** [comment]
Good catch!
