### ISSUE TITLE
Ability use out of combat

### ISSUE THREAD

**Issue by CalmKhaos** [AlderArts/foe#249]
I attempted to use a healing spell out of combat after I lost a party member in the drake fight and was met with an error:

encounter is null.........Entity.prototype.GetCombatEntry@file:///C:/Users/AJ/Desktop/foe/js/entity.js:2752:2
Ability.prototype.enabledCondition@file:///C:/Users/AJ/Desktop/foe/js/ability.js:246:35
Party.prototype.ShowAbilities/pushAbilities@file:///C:/Users/AJ/Desktop/foe/js/party.js:398:15
Party.prototype.ShowAbilities@file:///C:/Users/AJ/Desktop/foe/js/party.js:437:4
ShowAbilities@file:///C:/Users/AJ/Desktop/foe/js/exploration.js:331:2
Button.prototype.HandleClick@file:///C:/Users/AJ/Desktop/foe/js/button.js:78:4
Button/<@file:///C:/Users/AJ/Desktop/foe/js/button.js:60:3
Wb</</e@file:///C:/Users/AJ/Desktop/foe/js/raphael-min.js:10:3923

**Comment by aldergames** [comment]
Good catch!

**Comment by CalmKhaos** [comment]
You're welcome. Glad I can help.
