### ISSUE TITLE
Ability bug

### ISSUE THREAD

**Issue by CalmKhaos** [AlderArts/foe#252]
Trying out the new changes and clicked on the Skills button. Got this error to pop up:

ability is undefined.........AbilityCollection.prototype.OnSelect/prompt/<@file:///C:/Users/AJ/Desktop/foe/js/ability.js:333:8
zt@file:///C:/Users/AJ/Desktop/foe/js/lodash.min.js:9:357
Gr/<@file:///C:/Users/AJ/Desktop/foe/js/lodash.min.js:27:426
AbilityCollection.prototype.OnSelect/prompt@file:///C:/Users/AJ/Desktop/foe/js/ability.js:332:3
AbilityCollection.prototype.OnSelect@file:///C:/Users/AJ/Desktop/foe/js/ability.js:353:2
Button.prototype.SetFromAbility/this.func@file:///C:/Users/AJ/Desktop/foe/js/button.js:170:3
Button.prototype.HandleClick@file:///C:/Users/AJ/Desktop/foe/js/button.js:78:4
Button/<@file:///C:/Users/AJ/Desktop/foe/js/button.js:60:3
Wb</</e@file:///C:/Users/AJ/Desktop/foe/js/raphael-min.js:10:3923

**Comment by CalmKhaos** [comment]
Tried it again after a few of the new commits. Seems to be ok now.

**Comment by CalmKhaos** [comment]
Found a couple more ability bugs. It seems both Kick Sand and Provoke actually damage the enemy.

**Comment by aldergames** [comment]
Not actual bugs.

**Comment by CalmKhaos** [comment]
Oh, my mistake. Sorry about that.
