### ISSUE TITLE
I Don't Like MP Bars

### ISSUE THREAD

**Issue by PowerOfVoid** [AlderArts/foe#270]
Basically, it means that until I have enough MP to ignore the system, I spend most of my time using basic attacks, because doing that and healing after battle is almost always more efficient than trying to nova my enemies out with spells.

Especially when the spells don't do significantly more damage than stabbing people in the face.

Things I find more fun are:
* Combo-bars where you use setup moves to build power, and spend it on big moves. (MP bars with regeneration are like this; the moves that consume less MP than you regenerate are the setup moves)
* Rage bars that build power by damage being dealt to or by you.
* Explicitly having things at will

**Comment by aldergames** [comment]
Well, I'm not going to redesign the system. Those other things can be introduced, but on top of the current system, not replacing it.
