### ISSUE TITLE
[UI][Combat] Make it clearer whose turn it is

### ISSUE THREAD

**Issue by PowerOfVoid** [AlderArts/foe#274]
From #272

I often get confused as to whose turn it is.

![combat](https://cloud.githubusercontent.com/assets/3876355/7735684/b73fdc08-ff0c-11e4-980d-8d14a7b34ac4.png)

The UI could do a better job of helping me with this:

![tabs](https://cloud.githubusercontent.com/assets/3876355/7734386/a9ecee1e-ff03-11e4-8a52-095622a00f02.png)

**Comment by PowerOfVoid** [comment]
Tabs aren't the only option.

Putting a picture of whose turn it is in the text box would also do the job fairly well... as long as nobody has duplicate images.

**Comment by aldergames** [comment]
Perhaps just bolden the glow surrounding the active portrait (green in the image above, red for enemies).

**Comment by PowerOfVoid** [comment]
How about... this much glow:
![combat mod](https://cloud.githubusercontent.com/assets/3876355/7754919/564f0d12-ffbe-11e4-801a-3daed830c97a.png)

**Comment by aldergames** [comment]
How about that? The enemy is still a bit hard to see tho...

**Comment by CalmKhaos** [comment]
Is it possible to have this as a toggled effect? Kind of prefer before the change, if it's not too much trouble.
