### ISSUE TITLE
Weirdness in Kiai's first time buttsexing

### ISSUE THREAD

**Issue by LukaDoc** [AlderArts/foe#276]
“As ready as I will ever be,” Kia responds nervously.

“Good...” You smile at her encouragingly. “Now, get on all fours, and I'll give you a ride you are not likely to forget.” The elf complies, spreading her legs expectantly.

You equip your immense equine member, dressing it in lube to prepare it for imminent penetration. Kia throws nervous glances at you all the while, though whether because of second thoughts or impatience, it is hard to tell.

The last part says I "equip" my horsecock, which is very weird because I don't have any strap-ons, and actually have 3 dicks to pick from.

**Comment by LukaDoc** [comment]
Adding another bit of weirdness. Earlier in this scene it said my cock was too big to push all the way inside. Meaning I could only push it up to the middle.

Since my cock has a knot, later on it says that I knotted her. That should be impossible since the knot is located at the base of the shaft and I can only push it halfway in.

Suggest "increasing" Kiai's anal cap so it either fits all the way, or doesn't fit at all.

**Comment by aldergames** [comment]
There's some arcane stuff that needs overhauling in Kiai's capacity code. Should follow up on this before next release.

**Comment by aldergames** [comment]
The "equip" bit should be fixed a while ago at least. Closing this and pointing to #333 for the Capacity problem.
