### ISSUE TITLE
Felines typos/suggestions

### ISSUE THREAD

**Issue by CalmKhaos** [AlderArts/foe#281]
For your review. They are broken down by the interactions I had amongst them.

**-Jaguar- (Felines)**

You are wandering around the area when you come across a group of ***lounging, cat-like*** creatures.

They slowly get on their feet, stretching and flaunting their ***lithe, powerful*** bodies at you, their eyes never leaving their target.

There is no use in trying to avoid the jaguars' ***attention.*** ***You*** prepare yourselves for combat, shifting uncomfortably as your foes spread out, trying to surround you.

One of the jaguars flexes her claws menacingly, balancing on her hind legs, grinning as her tail sways playfully behind ***her. “Look*** what the cat dragged in, ladies,” the jaguar purrs confidently, her harem’s eyes glinting hungrily as they study your party. **(space was needed between ‘behind her’ and ‘Look’)**

The other **feline keep their** distance, but seem intent on watching whatever you are about to do. **(depending on the number of enemies, maybe change how the sentence is displayed? Feline/felines, keep/keeps, his/her/their)**

With a single thrust of your hips, you’ve pushed ***inside, her*** walls wrapping tightly around your shaft.

The jaguar's **companion are** looking on, perhaps in jealousy or apprehension, not that you care either way. If you still feel in the mood for it, perhaps you’ll give **them** a good fucking too. **(depending on the number of enemies, maybe change how the sentence is displayed? Companion/companions, is/are, him/her/them)**

“Why don’t you just give ***up…*** like good prey?” the jaguar purrs as he circles you. **(Thought it might have different type of impact this way. Your choice as always)**

It quickly dawns on her what your intention ***is as*** you start to stroke your free length, but at this point, the jaguar seems to be resigned to her fate.

**-Puma- (Felines)**

When you’ve finally deposited the ***last of your load*** into the willing feline, you wait a ***while – letting*** her savour the thickness of your shaft.

***No doubt you*** are acting quite differently from her usual mates – intimate and loving while still giving it to her hard and deep.

The puma gasps happily as you hit a particularly pleasant ***spot.*** ***Seizing*** the opportunity, you repeatedly thrust into her, relentlessly driving her toward a messy orgasm.

Finally, it is too much for her to ***take and*** she collapses on top of you, her slick girly juices dripping down around your big ferret clit-cock.

When she lifts a trembling hand to jerk herself off, you swat it away in annoyance. ***You tell*** her that you’ll maybe help her ***out – if*** she puts some effort into pleasing you.

**-Lynx- (Felines)**

When you are done, the ***lynx's*** entire front is thoroughly coated in your semen, so much so it’ll probably take at least a day to clean her fur after this.

The ***lynx's*** eyes jump open in surprise as the first jet of cum all but fills her mouth.

“Y-you are quite gentle, even though I **were** hunting you...” The lynx sounds perplexed at this, the prey showing mercy to the defeated hunter. **(looks like it may need a variable in place depending on the number)**

**-Wildcat- (Felines)**

Following your ***instructions,*** the wildcat pulls her ass cheeks wide, exposing her tight rosebud.

***It is*** more than ready for the task at hand, yearning to be plunged into the wildcat's blissfully tight hole.

A swat with your free paw cruelly denies her ***pleasure and*** she whimpers pitifully, wordlessly begging you to allow her release.

Always happy to introduce another slut to the joys of anal ***sex as*** you gleefully thrust your big clit-cock into her butt.

She adapts ***surprisingly quick*** to the rough pace you set, moaning appreciatively into her cunt.

The kitty is getting quite hot and ***bothered.*** ***You*** can see that one of her hands is busy between her legs, probing her wet pussy and pinching her clit.

She probably just needs ***practice –***  **lots** ***of practice.*** **(Thought to italicize 'lots' for emphasis. Bold might work too.)**

After the next few, the wildcat's front is thoroughly plastered in your ***jizz and*** the immediate area around her. **(Not sure how to approach it. Do you think this works versus the original?)**

She gasps for air, trying to swat off the thick ropes of spunk draping her ***face – only*** to have them replaced with your next shot.

**Comment by aldergames** [comment]
It should be noted that all of these scenes are the same (the jaguar/lynx/puma/wildcat share scenes).

**Comment by CalmKhaos** [comment]
I might have figured as much. This helped me keep track of what I was doing.
