### ISSUE TITLE
Restrict access to Bull Tower

### ISSUE THREAD

**Issue by aldergames** [AlderArts/foe#293]
Putting this as a long time issue until more of outlaws are implemented. Bull Tower should be restricted to after you have built rel with the outlaws through performing tasks.

**Comment by CalmKhaos** [comment]
What would be the new threshold to unlock the quest, if I may ask? I have an old save right at that point.

**Comment by aldergames** [comment]
Not implemented yet, and it would be balanced as to what actual tasks are available at that level. For example, current Aquilius tasks allow you to get Rep up to 30. Maria will be similar. I'd ballpark the lower reach for BT to be 25~ with this as a starting point. That may change down the line if additional tiers are introduced. At the very least, the upcoming "path into Rigard" will have to be finished before BT is unlocked.

**Comment by CalmKhaos** [comment]
All right, thanks for the info. Should be interesting to see how it all comes together.
