### ISSUE TITLE
Some Aquilius typos/suggestions

### ISSUE THREAD

**Issue by CalmKhaos** [AlderArts/foe#294]
For your review.

If the well-being of others weren’t at ***stake,*** I wouldn’t care what you did but since it ***is,*** I’m not going to stand for ***sloppiness.”*** **(was missing a closing quotation mark)**

“Decent work, Ky,” **Aquilius tells you, noticing your return.** **(italics run-on)**

Contained within is a clear, viscous liquid, and he picks up a long wooden stirrer and hands ***it*** to you without further comment.

“***Alcohol*** dissolves many things that plain water can’t, so that makes it important for cleaning and as a potion base,”

Must’ve been a particularly voracious kid, because next thing I ***know,*** I’m being apprenticed to a cobbler at the tender age of eight or nine.

Maybe my parents were hoping that I’d work enough to earn my keep for all that I ate, and if I ***didn’t,*** it damn well felt like I did anyway.

The farmers out on the plains, they do a shitload more work than I do to keep people alive and kicking by way of not starving to death, and you don’t see people expecting them to have great and wonderful insights about their ***professions.”*** **(missing closing quotation mark)**

“It wasn’t so long ago that doctors, surgeons and alchemists weren’t ***so*** highly regarded, that there were plenty of quacks, and even if you were the real ***deal,*** you’d to be careful to not end up doing more harm than ***good.”*** **(missing closing quotation mark)**

Something like… like city folk forgetting where their meat really comes from, and thinking it comes from the butcher’s instead of from inside a pig. You ***know?”*** **(missing closing quotation mark)**

He really had no stake in the whole business save holding membership - back in those days, if you weren’t a member of the guilds and did business ***anyway,*** they’d rough you up and shake you down - but that was enough.

Rioting’s all fun and games until someone dies, then everyone’s afraid that they’ll be the next in line to ***croak.”*** **(missing closing quotation mark)**

I don’t know how I was found out, though, but I must’ve ***been.*** ***On one*** fine day about five years ***back,*** I wake up to Zenith knocking on my door.

When the stuff in your guts leaks out and your very lifeblood gets infected, the only thing we can do is make your death as painless as ***possible.”*** **(missing closing quotation mark)**

“You want to know how it got started? Listen up then, for it’s going to be a long ***story.”*** **(missing closing quotation mark)**

Slowly, they began to get rarer and rarer, opening and closing more and more ***erratically.”*** **(missing closing quotation mark)**

If the merchants wanted one thing, you’d bet the king and the nobles would want ***another.”*** **(missing closing quotation mark)**

Before he could move against them, though, they managed to scoop up the queen - not Rhylla, the first queen - ***and*** tried to ransom her for political leverage. You can imagine how well he took to ***that.”*** **(missing closing quotation mark)**

Others didn’t know better, of course, and ended up in riots funded by the guilds, dying by the hundreds while the merchants tried to make an ***escape.”*** **(missing closing quotation mark)**

He wasn’t very discriminating either when he started hunting down the morphs who’d supported the rebellion, the fools who’d believed in the crap rhetoric the merchants had fed them, and plenty of innocent people ended up ***dead.”*** **(missing closing quotation mark)**

Oh, they had plenty to say, mostly to take their mind off the pain while I was sawing and ***sewing.”*** **(missing closing quotation mark)**

Poor bastard died on the ***spot.”*** **(missing closing quotation mark)**

“All hell broke ***loose.”*** **(missing closing quotation mark)**

In the end, they bled and died just like anyone ***else.”*** **(missing closing quotation mark)**

Some of the **free cities** also proclaimed they were willing to take in refugees from the civil war - some did flee down the King’s Road, although not many were willing or able to make the ***trip.”*** **(missing closing quotation mark)** **(A question about ‘free cities’ – Is it meant to be capitalized or not? Just a thought for when it pops up again.)**

The slums are still filled with those who lost their homes during the war, and those who lost their parents in the killing have only just begun to leave the orphanages in the last handful of ***years.”*** **(missing closing quotation mark)**

At least those of the old blood had a place in the system - we knew what duties were expected of the nobles, even if they didn’t follow through, and knew where to place the blame and file our ***grievances.”*** **(missing closing quotation mark)**

I like to think I’m not a violent man, but I damn well felt satisfied at their ***executions.”*** **(missing closing quotation mark)**

It takes work, but by Aria’s tits, it’s worth it. It is so worth ***it.”*** **(missing closing quotation mark)**

***Silence,*** save for the snores and murmurs of the injured out front, watching wisps of smoke curl upward and eventually vanish - ah, this is the life.

“Welcome, Ky,” **Aquilius says with a cordial nod of his head.** **(italics run-on)**

Happily, your ranger’s training in the lay of the land and its environs serves you well, your sharp gaze roaming from stand to stand and patch to patch as you wander off the beaten trails of the forest in search of the herbs Aquilius needs. **(What if the PC doesn’t have any experience in that type of training? Just a thought)**

“First one got turned into a moonshine distillery when I didn’t need it ***anymore***.”

You’ve got to keep everything perfectly ***balanced;*** else the whole house of cards ***come*** tumbling down.

The merchant guilds were bleeding money, barely managing to ***balance*** their books with the goods that still came back through the few portals that popped up, and with the loss of their wealth came the loss of their status in Rigard society.

“I don’t want to dwell on it ***anymore***,” Aquilius says all of a sudden.

**Comment by CalmKhaos** [comment]
Just remembered something else.

Aquilius eyes you uncertainly. *"I’m not exactly sure, Ky. After all, I’m ultimately responsible for those under my care, and you’re a bit of an unknown - but on the other hand, it’d be stupid of me to turn away good help. Tell you what - why don’t I get you started on the simple tasks first, then move onto the others when you prove yourself capable of not fouling up?”*

Still seem to get this line with my character despite how many times I have helped him. Also, his affection is in the high 70's at the moment too. I noticed that there is an 'else' line, but I haven't been able to get it.

**Comment by aldergames** [comment]
All of the "missing closing quote" ones are invalid; It's grammatically correct to write it that way if the same person continues talking in the next sentence.

**Comment by CalmKhaos** [comment]
Ah, I see. My mistake then.

**Comment by aldergames** [comment]
(What if the PC doesn’t have any experience in that type of training? Just a thought)

You cannot even get this quest unless you have ranger as an available job (ie Estevan trained you).

**Comment by aldergames** [comment]
else the whole house of cards come tumbling down.

The house of cards - singular, so comes should be correct.

**Comment by CalmKhaos** [comment]
Ok, I was just curious. Some of the other quests I happened to look through mentioned something pertaining to a class. Maybe I overlooked it...
