### ISSUE TITLE
Bastet typos/suggestions part 1

### ISSUE THREAD

**Issue by CalmKhaos** [AlderArts/foe#296]
For your review. Just a note about the honorifics: It is your choice, of course, but I went ahead and capitalize all instances of it, I think, based on its context. Also going to divide this into two issues since it is a little long.

A few hangers are provided for putting things up on, but other than that, ***there’re*** only four things of ***note:*** A simple three-legged ***stool, a*** full-body mirror against the furthest ***wall, a*** small ***switch, and*** an ornate magic circle on the floor in front of the mirror, just waiting to be activated.

For a ***moment,*** you are overcome with a sense of vertigo, as if you were free-falling. ***As*** quickly as it happened, it passes, and you open your eyes.

Between your ***legs,*** you have a sheath, hiding a feline-pecker which you know is about eight inches long and two inches thick when fully erect.

Between your flat ***buttcheeks,*** you have a virgin anus, right where it belongs.

***Overall,*** you’d say you look pretty attractive, but let’s not linger. As ***instructed,*** you approach the mirror and watch as your reflection is replaced by the image of endless sandy dunes before you.

You look back and see that the doorway has ***vanished;*** you’re left standing in the middle of the desert.

***Thankfully,*** you have fur to protect your skin, but that does little against the heat of the sun.

The envoy is meant to stay at the ***Lady’s*** temple, living a life of reverence and serving the goddess of love so that she may spread her ***love*** to all her faithful.

The covenant established between your village and the temple is that ***of*** a cat-morph, one of the people graced by the cat goddess herself, would be sent whenever needed.

***Usually,*** this happens once every century, though the specific amount of time may vary.

***Usually,*** the honor of serving the goddess would be reserved for a female - but this ***century,*** you were the only living cat-morph in the village, so you were chosen despite being male.

By ***now,*** you’d have given up, were it not for the temple located a couple feet away.

It takes a while, but soon ***enough,*** your ears twitch with the sound of the doors hinges scraping against each other as the grandiose door gives way to a cat-girl.

Twin statues of the goddess herself, a magnificently voluptuous female cat-morph, naked **save** for a shift about her loins, loom on either side of the front door. 

Her skin is pale as the moon, and even from where you ***stand,*** looks soft as milk to the touch, offset by the luxuriant black hair that adorns her scalp, ears and tail.

There is a world-wise maturity in her bearing, not diminished by the loving, yet slightly ***mischievous*** smile that curls her ruby-red lips.

“Ah, one of ***Lady*** Bastet’s holy children.

You do not bother to hide your surprise at the high priestess’ words; you were not aware that males had been sent to ***fulfill*** the covenant before.

For ***a moment,*** you visibly shrink.

***Humbly,*** you ask if that’s really possible, since your physique is... very much the opposite of the Lady’s own.

Everyone will take your words as our goddess’ ***own, so*** you should become accustomed to having people refer to you with female honorifics, ***Your Ladyship***.

That... makes sense, you suppose. Though ***privately,*** you are still unconvinced as to how well that will work, you politely assure Adala that you will do your best to grow accustomed to it.

***Gradually,*** you begin to notice a scent. The scent of greenery and water. When you look ahead, ***you*** realize that she’s taken you to a large bathing pool.

“There’s no need to be ashamed, ***Your Ladyship***,” she says with a soft smile, taking her ***belongings*** to a table just inside the hallway.

“It’s nothing I haven’t seen before, plus I’m flattered that you find me attractive, ***Your Ladyship***,

Lungs full to bursting, you plunge yourself into the cool water, trying to ***lie*** upon the bottom of the spring.

From the ***thigh,*** she continues patiently down your leg, rotating the knee until it clicks softly, then working the kink from your ankle.

“How do you feel, ***Your Ladyship***?”

“Please, wait here for a moment, ***Your Ladyship***. I’ll go make sure the preparations for the ritual are ***complete,*** then take you to the ritual chambers.

“Your ***Ladyship***?” You nearly jump out of your skin. You were so relaxed that you didn’t even hear Adala approach.

“Forgive me for startling you, ***Your Ladyship, but*** the preparations for the ritual are complete. Shall we go?”

“***Afterward,*** we will help you clean yourself of the remaining oil and you will be take to your throne, where you shall rule this temple as ***Lady*** Bastet herself,” she finishes."

***Normally,*** we’d have a small period of training for the envoy, to make sure they’re physically fit for this task, but that won’t be necessary in your case,

You’re a very handsome male, ***Your Ladyship, but*** I think we can both agree that you still lack a few of the visual qualities of our goddess, Lady Bastet.

***Unthinkingly,*** you cup the imaginary bulge of your prodigious breasts, trembling with fantasized pleasure.

**tooltip for No** - ...This is but a small sacrifice for the many blessings ***Lady*** Bastet has granted you and your village.

You promise her that you will do whatever she asks so that you may ***fulfill*** your role.

“Of course, ***Your Ladyship***. Never forget that we’re here to serve you. We’ll do our best to make sure you’re comfortable and want for nothing,” she says, bowing reverently.

Of course, ***Your Ladyship***. We have time, but please try not to delay for too long.

“Yes, ***Your Ladyship***. Please follow me,” she says, extending her hand.

Then, Adala triumphantly pushes open the door and you are too awestruck to think about such things ***anymore***.

“Your ***Ladyship***, let me introduce you to your personal attendants,” she says motioning to the twins.

“It’s an honor to finally meet you, ***Your Ladyship***,”

**Comment by LukaDoc** [comment]
1st suggestion should remain as "were". I think it sounds best.

2nd: Missing word = love.

3rd: "save" is what it should be.

**Comment by CalmKhaos** [comment]
Fair enough on those points. Thanks for your insight.
