### ISSUE TITLE
Bastet typos/suggestions part 2

### ISSUE THREAD

**Issue by CalmKhaos** [AlderArts/foe#297]
“Thank you, ***Your Ladyship***,” they reply in unison with a grin. ***They*** walk towards the altar, kneeling besides it and motioning for you to hop on.

“Yes, ***Your Ladyship***.” Adala moves to pick up one of the ***jars while*** the twins stand beside you. “We’ll start on the top. ***Please,*** close your eyes, ***Your Ladyship***.”

No sooner have your eyes fallen ***shut,*** warm liquid begins gently pouring over your face.

“Open your mouth, ***Your Ladyship***,” whispers one of ***twins*** into your ear.

Without ***hesitation,*** you part your jaws, letting the oil flow directly onto your tongue. It’s thick and rich, almost like honey in its consistency, and just like ***honey,*** it tastes wonderfully sweet.

At ***once,*** your eyes spring open, revealing that you are locking lips with the luscious Adala.

“The changes have already started. How do you feel, ***Your Ladyship***?”

You sound... girlier, than you remember. It’s such a soft and dainty ***voice, but*** it’s melodious, too.

“I’m glad to hear ***it***. We will be moving on to your chest now, ***Lady*** Bastet.”

“Sorry, ***Your Ladyship***. I couldn’t resist,” she says with a mischievous smile. You gasp once more as her naughty little twin does the same to your other nipple. “Forgive me, ***Your Ladyship***,” she says with a mischievous smile of her own.

“Of course, ***Your Ladyship***. We’re here to serve,” says Ming. “And serve we shall.” says Ling.

Blood rushes under your skin, making your nipples swell proud and firm, all the ***sign*** that the catgirls need.

It is as if you ***are…*** are being invigorated by the worship of your priestesses! **(It looked like a stutter-like instance. Would this be ok?)**

“I’m pleased to hear that, ***Your Ladyship***,” says Adala, stopping her attentions on your midriff.

“May I, ***Your Ladyship***?”

A luxuriant purr rumbles out of your belly as you feel soft, ***dexterous*** fingers playing lazily around your manhood.

“Lose this part? What do you mean, ***Your Ladyship***?”

“Forgive me, ***Your Ladyship***,” she says, stifling her laughter.

Lady Bastet is the goddess of love, and as ***such,*** she has many aspects.

Tell me, ***Your Ladyship***, which aspect do believe to be your true aspect?

No, ***Your Ladyship.***

So they just pick one of your many aspects, ***Your Ladyship***.

But as the goddess of ***love,*** you must also have the means to show your faithful that you love them, and could you do that if you were not properly equipped to do so?

***Usually,*** it’s a lot of work making sure a worthy penis grows, but in your case, ***Your Ladyship – you*** already have such a beautiful one...

“Simply anoint it, ***Your Ladyship, unless*** you don’t mind me playing with it a bit. If I must confess, I’ve had my eye on your cock ever since I saw you in the bath, ***Lady*** Bastet.”

**tooltip for Absolutely** - You’re so horny right ***now,*** you’d have to be crazy to deny her. You expect her to play with it like she plays with her favorite toy.

“You honor me, ***Your Ladyship***,” Adala says with a grin, fetching a small vial of oil and what looks like a small funnel.

We need to make sure every inch of your body is anointed, ***Your Ladyship***.

Adala ***starts*** by pouring a healthy dose of oil on your penis and balls, then she closes the vial and begins massaging your shaft.

***Next,*** she takes your shaft in ***her*** hands, gently rubbing your tip and opening your urethra.

By the ***Lady***, there are no words to describe how alien it feels to have fluid going in when normally it would be coming out!

Within a ***heartbeat,*** she is orally worshipping your straining balls.

***Noisily,*** she kisses them, one by one, then starts to suckle upon them.

She tries - by the ***Lady’s*** bounty, she tries so hard.

“Thank you for this boon, ***Your Ladyship***.”

Ming, Ling, please anoint ***Her Ladyship’s*** legs.

“Yes, ***Lady*** Adala,” the twins reply in unison, each grabbing a pitcher full of oil.

Two sets of eyes flick towards your dripping dick, matching mischievous grins spreading on identical ***faces, but*** the twins remain professional.

“For your butt, ***Your Ladyship***. We must anoint inside you as well,” she explains, rubbing some slick oil on the tip of the dildo.

“Of course not, ***Your Ladyship***. We haven’t even started molding your pussy. We use the same dildo for both tasks.”

“No need to worry, ***Mistress*** Bastet. Just sit back, spread your legs and relax. I’ll make sure you enjoy your anointment.”

Giggling, you assure her that you have no doubts about that, before noting you’re happy to ***lie*** back for her, but you currently can’t do anything about spreading your legs.

“May I, ***Mistress*** Bastet?”

Far less than you’d expect for a dildo that ***size, especially*** when you consider you used to be a virgin prior to this.

“Any takers for ***Her Ladyship’s*** pussy?” Adala asks, lifting the still dripping dildo up in the air.

“Don’t worry, Ming. We can handle ***Mistress*** Bastet’s butt and her back,” the head priestess says, giggling.

“***Your Ladyship***, please turn around,” Adala asks.

Adala’s hands busy themselves with molding your once flat ***rear, but*** you can feel your tush growing under her fingers. Firm, round, ***and*** with just the right give to make it a thrill to hold. **(Changed ‘butt’ to ‘rear’ to allow ‘,but’ instead of ‘butt, but’. Is this acceptable?)**

Right about ***then,*** Ling decides to start molding your new ***vagina.*** ***She*** massages the flesh just behind your balls, making circular motions with a pair of fingers as if she was spreading and closing pussy lips.

It feels strange, at ***first, but*** also rather nice. ***The*** more she massages, the nicer it feels.

“Yes, ***Your Ladyship***,” she replies.

The feeling is like when Adala had it up your asshole... ***but*** at the same time, it’s totally different.

“Please, ***Lady*** Bastet. Wait here, I’ll go fetch a mirror for ***Your Ladyship***,” she says, hurrying off.

“Here, ***Your Ladyship***,” announces Adala, carrying a full-body mirror.

**Comment by LukaDoc** [comment]
Yes on both suggestions.
