### ISSUE TITLE
Alchemy UI improvement suggestion

### ISSUE THREAD

**Issue by KeratinStench** [AlderArts/foe#299]
At the moment, creating a potion results in a screen telling you it's been created successfully and a "Next" button returning you to the alchemy menu. If you want to use that potion, you need to navigate to the "Items" menu and find it there.

It would be more convenient if there were two extra buttons on that screen - a "Use" button that works in the same way as selecting a potion in the Items menu, and a "Repeat" button that is enabled when there are enough materials for creating another potion of the same type. I think adding both buttons would require relatively little effort.

**Comment by PowerOfVoid** [comment]
This issue is a child issue of #232

**Comment by aldergames** [comment]
This is in essence fixed with the batch brewing addition.
