### ISSUE TITLE
More Asche typos/suggestions

### ISSUE THREAD

**Issue by CalmKhaos** [AlderArts/foe#311]
For your review.

Customer is going to be seeing things from this **jackaless’s** perspective… and she yours.**(Noticed farther down, there is another instance of “jackaless’”. Would this one follow suit as the other?)**

Coupled with the heat of **her skin** on your own, the sensations form an intense wildfire that throbs and pulses against your ‘skin’, inspiring you to work harder. **(Checking context of skin here?)**

Completely addled by now, her eyes rolled back into her head as she pants and yips in pure, unadulterated pleasure, Asche quivers from head to toe, causing her jewelry to clink, as the jackaless ***cums***.

Utterly spent and exhausted, the two of you are content to just lie against each ***other with*** Asche slumped on top of you, her ragged ***breathing*** tickling your neck as she recovers. **(If ‘with’ isn’t good enough, perhaps ‘lie against each other as Asche is slumped on top of you’. Your thoughts?)**

You feel a coolness on your face as Asche’s sweet honey dries on your **skin**. **(Checking context of skin here?)**

Fond or not is one thing, but we are all doing things ***we*** are not fond of to be getting through days, yes?

Slinking up to you, Asche grabs hold of **your thighs, one in each hand, and pulls them apart with surprising strength.** The jackaless eyes your crotch and the ‘cocks’ on offer, kneading the gentle flesh of **your inner thighs** as her fingers creep ever closer to your ‘shaft/s’.**(Tagging for different lower body)**

With a blur of motion and clink of ***jewelry***, she’s on you.

The jackaless’ smooth, golden fur slides against **your skin** as she settles into place, her maw opening wide to take your shaft. **(Checking context of skin here?)**

Spirits above, you can *feel* her ***marvelously*** warm and wet insides milking away at your ‘cock’.

Asche shakes her head from side to side, her muffled cries growing louder, and as you are treated to the first-hand experience of swallowing so much of your own hot, sticky cum, you sure can ***sympathize***.

With one swift motion, Asche grabs hold of **your inner thighs, one in each hand, and forces them apart to** expose your bare muff and the ‘vag’ nestled **between your legs**. Trailing her hands along **your thighs** before returning them to her sides, the exotic jackaless begins to rub herself before your eyes, one hand teasing her increasingly damp slit while the other roams around the rest of her body, touching breast and belly alike in long, languid strokes. **(Tagging for different lower body)**

Whatever Asche does to herself, it’s as if it’s being done to you as well: **when she gives her clit a gentle flick, you feel her invisible fingers against your button**, you squirm and moan under her tender caresses - even as she does the same. **(Tagging for if clit-cock)**

Her nose and tongue share the workload of getting you all nice and lusty; the former grinds against **your clit**, sending sparks of sensation racing along the golden lines traced on your body, then she tilts her head back and sends the latter probing like a lewd, long tentacle into your heat-filled slit. **(Tagging for if clit-cock)**

Despite her impressive ***efforts,*** you’re not one for passively receiving. Gently but firmly, you place a hand between Asche’s ***shoulder blades*** and push the jackaless down, low enough that her nipples graze the mattress’ silken fabric as she laps at your cunt.

Throwing your head back and crying out in climax, you send a squirm of thick nectar straight ***at Asche, soaking her face and muzzle***. **(Thoughts on this change?)**

Without waiting for your reply, Asche sinks down onto you, leaning the weight of her upper body onto your hips **and thighs** as she sandwiches your stiff ‘cock’, shaft well between her generous mounds. **(Tagging for different lower body)**

Does **pretty** customer want to sample Asche’s new tits? **(Tagging for handsome/pretty)**

“Then just to be closing eyes and feeling the magic, **pretty** customer.” **(Tagging for handsome/pretty)**

**Pretty** customer is a very special person; spell has never worked this well before. **(Tagging for handsome/pretty)**

Arching her back, the jackaless pulls herself free of you, milk spattering all over the mattress, her, ***and*** you…

You cry out as well, sharing her pleasure and riding her orgasm, and tremble from **head to toe** before finally going limp, as utterly exhausted as your sexy, exotic lover is. **(Tagging for different lower body)**

“Is being all right, Asche is also big fan of many things, so customer is being assured that **she** is in good hands.” **(Checking context here? It sounds like Asche is referring to the PC)**

Customer is feeling this jackaless’ pleasure in addition to **her** own. Can be learning much from feedback - if you are having hands ***free,*** maybe I am asking you to be taking notes, yes? **(Tagging for context check)**

Nothing heavy, just a quick peck, and yet you feel heat growing in your cheeks and just above your ‘breasts’, a liquid heat that throbs and bubbles under **your skin**. **(Tagging for skin context)**

Each time your **swollen clit** passes Asche’s, a shudder of pleasure runs through your very being, compounded by the empathic magic that the jackaless worked upon both your bodies. **(Tagging for if clit-cock)**

The mattress beneath you is already slick with a puddle of your combined ***girl-cum***, and trapped as you are under Asche, all you can do is squirm and struggle in the throes of pleasure as the exotic shopkeeper yips and whines atop you, the fur about her crotch and thighs matted with the same glistening mixture.

“So, did customer enjoy lesson?” the ***jackaless*** purrs, her voice rich and honeyed as she begins the arduous task of cleaning herself up.

**else line** - yes, you definitely feel like you understand your actions and their results more, and perhaps with a little ***effort,*** can put that knowledge into giving and receiving pleasure.

**Comment by aldergames** [comment]
Slinking up to you, Asche grabs hold of your thighs, one in each hand, and pulls them apart with surprising strength. The jackaless eyes your crotch and the ‘cocks’ on offer, kneading the gentle flesh of your inner thighs as her fingers creep ever closer to your ‘shaft/s’.(Tagging for different lower body)

Actually works (check the requirements for the scene at the top).

**Comment by CalmKhaos** [comment]
I must have missed that... I'll look again.

**Comment by aldergames** [comment]
options.push({ nameStr : "Get Oral",
		tooltip : "She certainly has a nice, long muzzle… wonder if her tongue’s just as good.",
		func : function() {
			Scenes.Asche.Sex.GetOral();
		}, enabled : player.Humanoid() && (player.FirstCock() || player.FirstVag())
	});

**Comment by CalmKhaos** [comment]
Yeah, I just saw it. My mistake.
