### ISSUE TITLE
More Asche typos/suggestions

### ISSUE THREAD

**Issue by CalmKhaos** [AlderArts/foe#313]
For your review. I seemed to have missed these in the last overview I did, discounting the italics issue recently discovered.

A wide, predatory grin plastered on her muzzle, she presses down on you, pinning you to the mattress with all four limbs while her hips descend squarely upon yours, pressing your shaft against your stomach and getting **them** out of the way. **(Showing for PC with 1 cock)**

You can’t hold on long, and your orgasm is unexpectedly sudden and intense when it does come, the insides of your very flexible pussy clenching about nothing in painful tightness, **your cock releasing their load** all over the place in strings and spurts. **(Showing for PC with 1 cock)**

Now that’s some concrete information for once. Is there anything else he can tell you? **(italics run-on)**

Yes, it is a specimen of nightshade! **(italics run-on)**

**Comment by CalmKhaos** [comment]
Just bringing this to your attention.

Yes, it is a specimen of nightshade! (italics run-on)

Still is in the game as of this mentioning. I figure that one of the words is italicized, but it wasn't closed.

**Comment by aldergames** [comment]
Where is this exactly? I can't find it anywhere in code.
