### ISSUE TITLE
Quest read out Helping Aquilius

### ISSUE THREAD

**Issue by Akhter13** [AlderArts/foe#324]
Helping Aquilius

Help Aquilius gather herbs from the forest.

Gather herbs from the forest for Aquilius. You should be able to find them pretty close to the Outlaws’ camp.
In addition, Aquilius asked for some ERROR. While not strictly necessary, you’re sure the old surgeon would appreciate you getting that as well.
Return the herbs to Aquilius in the infirmary.

This is grayed out in all modes and not struck through, despite having been completed. It may be unrelated but the last line of each Asche task is also not struck through, but is correctly flagged complete.

Fresh Ginseng

Help Asche find some fresh Ginseng.

Go to the Highlands on the other side of the plains and search for fresh Ginseng.
Return the Ginseng to Asche in her shop in Rigard.
Nightshade

Help Asche find some nightshade.

Maybe find someone knowledgeable of forest herbs and ask them where one could find nightshade?
Go to the Forest and find some nightshade.
Return the nightshade to Asche in her shop in Rigard.

**Comment by aldergames** [comment]
Can you verify if the Aquilius thing shows up outside of DEBUG mode? It is a repeatable quest, so it shouldn't show at all while you're not actively on it.

**Comment by Akhter13** [comment]
it disappears outside debug modebut the last lines of each of Asche's quests still remain unstruck through [frankly a minor point] 


     On Thursday, 25 June 2015, 5:38, aldergames <notifications@github.com> wrote:
   

 Can you verify if the Aquilius thing shows up outside of DEBUG mode? It is a repeatable quest, so it shouldn't show at all while you're not actively on it.—

**Comment by aldergames** [comment]
The latest github version should have them struck.
