### ISSUE TITLE
Is Nagazm unfinished?

### ISSUE THREAD

**Issue by KeratinStench** [AlderArts/foe#339]
Looking at the code, all it seems to do is give the character a snake tail. The Naga is a busty hermaphrodite with a double penis, so there's a bit of missed potential there...

**Comment by KeratinStench** [comment]
I've started work on improving Nagazm. I will make a pull request when I'm ready. Could you please have a look at the tasks I've outlined as comments here https://github.com/KeratinStench/foe/commit/e1400414b9b44d18c887eba4f5a555a45058a544 and give me some feedback. For now, I think that hermaphroditism has the highest priority, since the game doesn't seem to pay much attention to things like eyes and tongues yet.

**Comment by aldergames** [comment]
Changes are merged (made some additional tweaks, including tweaking RemTail so that it works as intended). Thanks for the help!
