### ISSUE TITLE
ArrivalOpheliaTalk scene can be avoided

### ISSUE THREAD

**Issue by mirhl** [AlderArts/foe#346]
When I arrived [here](https://github.com/AlderArts/foe/blob/454d3ac05e27467e56114518ea56ddbe9d596d4c/js/loc/burrows.js#L538) I saved the game. Then I'm pretty sure the dialog was no more and I could leave without problems. 

I could notice I had miss something [here](https://github.com/AlderArts/foe/blob/ce6110113cec0dc66cb8c758d36bb1ad815875fa/js/event/burrows/ophelia.js#L423)

Anyway to fix my save now then?

**Comment by aldergames** [comment]
Uh, you are doing something weird. How are you triggering the scene exactly? The Data prompt menu should never be visible when this scene is triggered.

**Comment by mirhl** [comment]
Well, it's visible.

**Comment by aldergames** [comment]
Again. How are you triggering the scene?

**Comment by aldergames** [comment]
I have at least not been able to reproduce this in any of the ways it can be triggered:
* Fight win, seduce
* Fight loss
* Manual approach

**Comment by mirhl** [comment]
Oh, in that sense. 
Fight, win, seduce, follow
