### ISSUE TITLE
Duplicate RemBalls functions and a possible bug

### ISSUE THREAD

**Issue by KeratinStench** [AlderArts/foe#348]
In tf.js, there are TF.ItemEffects.RemBalls() and TF.RemBalls(). Is this intentional? The first one uses RemoveAppendage internally, and it looks like it doesn't work, e.g. when invoked with:

```javascript
Items.Nagazm.PushEffect(TF.ItemEffects.RemBalls, {odds: 0.5, ideal: 0, count: 2});
```

**Comment by aldergames** [comment]
Copy paste error I think.

**Comment by KeratinStench** [comment]
I still can't make the transformation work for some reason, even if I set the odds to 1. I'm in debug mode, using the cock-smith to add testicles.

**Comment by aldergames** [comment]
Once again, my bad. Error was in js interpretation of "null" values. ie

var ideal = opts.ideal || 2;

When ideal was 0, this would become 2.
