### ISSUE TITLE
Lei petting typos/suggestions

### ISSUE THREAD

**Issue by CalmKhaos** [AlderArts/foe#363]
Your breath catches as Lei's **fingers** trace slowly along your cheek, before he moves his **hand** further up, stroking your hair. The motion of his **fingers** is gentle; they barely press against your [hair], tickling more than brushing. You wonder what he'll do next, but once he reaches your neck, he simply shifts his **hand** back to the top, and starts over. **(‘finger’ and ‘hand’ repeat)**

You're a little disappointed at first, but gradually, as his **fingers** trace stroke after stroke over your scalp, you feel a warmth spread through you. The steady movements are pleasant, almost hypnotic, and you drift into a pleased daze as Lei pets you. **(Possible ‘finger’ repeat)**

Feeling rather awkward, you try to purr, imitating the sound you've heard cats make. You don't get it quite right at first, but after a few more ***attempts,*** you're purring well enough that you could trick a cat.

It feels peculiarly good, a release of tension from the center of your being, as your muscles relax and your world narrows to his **hand** on your hair, and this sound of pleasure coming from inside you. **(Possible ‘hand’ repeat)**

<i>“Good [boygirl],”</i> Lei says quietly. His **hand** moves down a little, and[, shifting your hair aside,] scratches behind your [ear], and you tilt your head towards him in pleasure. **(Possible 'hand' repeat)**

**Lei smiles, and with a turn, moves towards the bed, and sits down, pulling you after him into his lap.** You look up at him, wondering what he’s planning, but he only holds you. **(Maybe a little tweak for this? Think it might be better broken up somewhat?)**

You wait for Lei to finish one of his strokes, before grabbing hold of his right arm, and nibbling on the **hand**. You worry at the skin for a few moments, and then take a bigger bite, taking the knuckle of his thumb between your teeth. Keeping firm hold of the **hand**, you glance up at him out of the corner of your eye. **(Possible ‘hand’ repeat)**

**To your surprise, you see him grinning, and after a moment he bursts into laughter, the sounds of his mirth filling the room.** You tilt your head in puzzlement, inadvertently shifting his **hand** along with it. **(Maybe a little tweak for this? Think it might be better broken up somewhat? Possible ‘hand’ repeat)**

Apparently undeterred, Lei strokes your hair with his other **hand**. <i>“I didn’t know I had such a selfish, playful kitten,”</i> he says. <i>“How about this, then?”</i> He grabs you around the waist with his free arm, and with a ***twist,*** tumbles both of you onto his bed. You let out a startled yelp as you fall, releasing his **hand** from your jaws, as you fall down on top of him. **(Possible ‘hand’ repeat)**

**After a minute, you quiet down, and Lei sits up, pulling you along with him, leaving you sitting in his lap, held tight in his arms.** You look up at him, wondering if he’s plotting something else, but he only holds you. **(Maybe a little tweak for this? Think it might be better broken up somewhat?)**

The two of you stay entwined for a long time, and you begin to feel drowsy in the small dark room, with candles flickering around you. **Your leg feels like it’s falling asleep too, and you move it, shifting position a little awkwardly**. **(Naga?)**

**Comment by aldergames** [comment]
Note for coding: do quest log at the same time.
