### ISSUE TITLE
Nagazm legs transform bugged

### ISSUE THREAD

**Issue by Zaknod** [AlderArts/foe#365]
In V0.4j, using the Nagazm and obtaining the Naga Lower body(Serpent Tail replacing legs) after you save and re-load, the tail turns to reptile tail and your legs become reptile legs ending in clawed feet. Dunno if that is intentional, but it seems a bit uncouth after spending hours grinding the fair way to get the Naga look without utilizing the Debug option.

**Comment by aldergames** [comment]
Removed unrelated comments.
