### ISSUE TITLE
Layla logical error

### ISSUE THREAD

**Issue by trixymoon** [AlderArts/foe#370]
When you click on "Appearance" on Layla menu after you recruited her you got the scene "Scenes.Layla.FirstTimeSkinShift();" then when you do sex with her for the first time you got the same scene again.
file layla-sex.js line 102:
<pre>if(layla.flags["Skin"] != 0) {
</pre>
I think the check was
<pre>
if(layla.flags["Skin"] <b>==</b> 0) {
</pre>

**Comment by aldergames** [comment]
Right you are!
