### ISSUE TITLE
Not a bug: Inventory redundancy

### ISSUE THREAD

**Issue by trixymoon** [AlderArts/foe#376]
I was thinking, given the fact that all the items inside the inventory start with the same "it" key, and the only other informations for every items is the quantity number..
<pre>"inv":[{"it":"staff2","num":1},{"it":"deer2","num":21}, ... ,{"it":"wolf3","num":116}]</pre>

You think it is possible to shorten the inventory in this way?
<pre>"inv":{"it":{{staff2":1},{"deer2":21}, ... ,{"wolf3":116}}</pre>
In this way, search for an item in the inventory it takes O (1) while currently is O (n)

Obviously if you have to cost much effort to change the code discards this my suggestion without problems.
Giulio.

**Comment by kspriv** [comment]
What he's using is called JSON (feel free to look it up for more information), which is definitely the way to go.

The alternative you described doesn't make much sense. The curly braces represent an object - so in your notation you're saying the property "staff2" has a value of "1". If what you were trying to go for is a notation that doesn't store the items as objects, but instead as arrays of data it would look more like this:
"inv":[["staff2",1],["deer2",21],["wolf3",116]]

That format does save some space, but you don't know what each one of those arrays of data are supposed to represent. What is "staff2"? What is 21? In the JSON above he had them associated with object properties. He could pass that string to any language that can understand JSON and have it turned into the appropriate objects of that language with no effort on his part. In the array example he would have to write a translator/builder of some sort to attach properties to the values.

If your goal was to give constant lookup time for an item, that's a different issue. If you wanted constant lookup time by item name it would be something like:
"inv":{"staff2":{},"deer2":{},"wolf3":{}}

However, that would only work with name. Searching for any other item property would put you back at O(n) lookup.

**Comment by aldergames** [comment]
This is only for the save format tho... In the game itself, the inventory object holds a set of items. Those  have "it" and "num" keys, and the values for those are the actual item (not it's ID) and the number of items you have. I can't index the table with an object as a key though... so I'd have to:
* Store the item ID as the key (the same as is in the save format). This would mean that anytime you wanted to do something with the actual item though, you'd have to index another table (ID-to-object). This'd be a hassle.

**Comment by kspriv** [comment]
Not saying it should be done, but you'd technically just need to make a few methods for managing items (add, update, remove, ..?). Once they were written, they'd manage the item array and any maps you have without any effort on your part.

Regardless, this is pointless when you're dealing with so few items. O(n) is perfectly fine for lookups when you're dealing with lists this small.

**Comment by aldergames** [comment]
Gah, shouldn't write posts when this tired... I understand what you meant in your previous post kspriv, thinking it over a bit, that's how I would do it now. But yeah, probably not worth it. It _could_ be possible to reduce the save format from [{it: ID, num: NUM},...] to {ID: NUM,...} (as I haven't really used anything other than num-of-items in the save, and am unlikely to), but it's always a hassle to change the format in the middle. Probably not worth the additional bytes it would save.

**Comment by trixymoon** [comment]
Well, Kspriv I know what json is. "The curly braces represent an object" -> hashmap.
My suggestion was a nested hashmaps, I forgot close bracket '}' at the end.
The error on my part was the implicit representation of the quantity of the items as the value of the item itself.
Eg:  {"wolf3":116} I have 116 objects of wolf3.
Which is conceptually wrong because I lose information: the information of the quantity of the items shift from the json file to the code.  
So the whole idea was hashmap "inv" where inside was a bunch of nested hashmaps representing the items (the last example at the end of the first comment kspriv)
Ps. I the inventory is always ordered you can use binary search for O(log n) complexity
The initial premise was, however, that if it cost too much work then it is not worth. Change the format of something in the middle is always a pain...

**Comment by aldergames** [comment]
Closing this for now. It might be an interesting prospect in the future if we are running out of saveformat space, but for now I don't think we need to worry about the performance of the searches (the inventory is pretty tiny, after all).
