### ISSUE TITLE
[0.4n] Rosalin doesn't accept the ingredients for Anusol

### ISSUE THREAD

**Issue by NeitherMeNorYou** [AlderArts/foe#377]
To make things short: Rosalin had the scene to tell my PC about the Anusol, and sent her to get the ingredients (Snake Oil, Fruit Seeds, Spring Water), but while my PC has those items in the inventory I can't seem to trigger a new scene to combine them, or to talk to Rosalin about it at all.

**Comment by CalmKhaos** [comment]
http://www.fenoxo.com/?p=455

Alder made an update on this saying that he made an error about it. The fix is up on the Git version. He also mentioned that he wanted to wait a bit for some other things before releasing another version.
