### ISSUE TITLE
harthon pregStage logic error

### ISSUE THREAD

**Issue by trixymoon** [AlderArts/foe#379]
file/line: https://github.com/AlderArts/foe/blob/master/js/event/halloween.js#L4356
<pre>
if(pregStage <b>&gt;</b> 5)
</pre>

because Harthon hasn’t give birth jet.

_________________________

file/line: https://github.com/AlderArts/foe/blob/master/js/event/halloween.js#L4400
<pre>
	if(pregStage &gt; 0<b> and pregStage &lt; 6</b>)
		Scenes.Halloween.HW.harthonPreg++;
</pre>
_________________________

file/line: https://github.com/AlderArts/foe/blob/master/js/event/halloween.js#L4021
<pre>parse["bloated"] = (pregStage &gt; 0<b> and pregStage &lt; 5</b>)? " bloated" : "";</pre>
_________________________

file/line: https://github.com/AlderArts/foe/blob/master/js/event/halloween.js#L4044
<pre>if(pregStage <b>== 1</b>)</pre>

Harton is impregnated only once
_________________________

file/line: https://github.com/AlderArts/foe/blob/master/js/event/halloween.js#L4495

<pre>parse["g"] = (pregStage &gt; 0<b> and pregStage &lt; 5</b>) ? " gravid" : "";</pre>

**Comment by aldergames** [comment]
What is the error?

**Comment by trixymoon** [comment]
The game shows Harton as pregnant even if she has already given birth.

**Comment by trixymoon** [comment]
while in line 4044 you have already make her pregnant
in line 4358 is ">" and not ">=" (sorry for the previous typo)
"Your daughter coos softly, ..." but if  pregStage == 5 then Harton had not given birth yet (condition at line 4403 if(Scenes.Halloween.HW.harthonPreg == 5) { )
So the game show you your daughter before Harton give birth to her.

Sorry for the messy comment

**Comment by trixymoon** [comment]
while the line 4400 is only to avoid the indefinite increase of the variable: Scenes.Halloween.HW.harthonPreg++;

**Comment by aldergames** [comment]
It kinda won't happen though... since when you enter that scene with 4, 4401 will increment to 5 and immediately trigger the birth event.

**Comment by trixymoon** [comment]
Yeah re-reding the code. You are right! Sorry
