### ISSUE TITLE
Vaughn's Third  Task.

### ISSUE THREAD

**Issue by Dragurn** [AlderArts/foe#383]
1. I can't seem to find the command for poisoning the food in The Lady's Blessing. I deleted and download the again (I play the offline version F.Y.I.) and then loaded a save file but still I wasn't able to complete the quest.
Here are the details:
I. I chose poison.
II. The quest was taken at 7th of Autumn 4:25.
III. I immediately went to the inn and waited until the deadline.
IV. I tried everything but it didn't work.
2. I don't know how the bug can be reproduced, sorry.
3. There is no error message, sorry.
4. https://drive.google.com/open?id=0B3YG7Q2lLtSAZVRMRUdoU2wwdTQ for the saved file in order to reproduce bug.

**Comment by aldergames** [comment]
The thing is, the event is set to trigger when you ENTER the inn, meaning that waiting inside won't work. Kind of a hassle, I know.

**Comment by theobserver12** [comment]
If you can set it such that waiting there will do it, the opening scene can easily be tweaked for both situations.

**Comment by aldergames** [comment]
Solved!
