### ISSUE TITLE
[BUG]  Canis root not recognized during Jeanne's Estros alchemy mixing.

### ISSUE THREAD

**Issue by jerricho13** [AlderArts/foe#404]
Jeanne does not recognize the canis root in player's inventory so Estros can not be mixed/learned.  

NOTE:  In the requirements for Estros, only the word "canis" is displayed vs. "canis root".

**Comment by aldergames** [comment]
Uh... dunno what you are talking about. The recipe for Estros is: Vulpinix+Homos+Bovia. Did you mean Testos? If so, the recipe for that one is Equinium+Homos+Canis.

Yes, there is an item named Canis.
