### ISSUE TITLE
Bunch of Typos

### ISSUE THREAD

**Issue by filllosof** [AlderArts/foe#411]
Zebra Genseng Encounter
Choosing ‘Fight’ after trying to seduce them
They dare reject your advances? *Fie*! Lunging at the shaman with a growl, you tackle him to the ground even as his fellows grab their staves and run to his aid.

It’s a fight!

Lagon
Begging him after BJ
As you are bent over and getting railed, you notice that some of Lagon’s children have moseyed their way over to get a closer look, some giving you jealous glares. “It seems like you’ve gathered the attention of my daughters, my little slut,” the king grunts in your ear. You raise your eyes, and sure enough, two pretty lagomorph *does* are standing nearby beaming down at you. “We wouldn’t want to deprive them of their treats, now would we?”

Maria
First Dead Drop (multiple companions)
You take a moment to settle down your companions, telling *her* to just kick back and relax for a moment in the camp while you run this errand. Watching her trundle off into the camp’s main body to do what she needs to do, you fall in behind Maria, ready to set out.

Terry
Drinking Milk
Looking over Terry’s chest, you see the undeniable curves of her perky breasts. The fluff that would usually cover her nipples has since receded, exposing the bottom *of* half of the vixen’s cleavage. There’s still plenty of soft fur for you to play with, should you feel inclined to.

Catching anal

*She* nuzzles you softly, the new position helping *him* go deeper inside you. You can feel her knot batting your juicy flank, as if asking to be allowed in. Yet Terry makes no effort to push past your barrier. “How does this feel?”she asks, hugging you from behind.

Isla
Talking about her tribe

“My tribe, we’ve got a stone circle. The zebras, they’ve got a spring. We mustelids dance to bring the rain, and the jackals dance to drive it away. I’m sure the minotaur do their own rituals and have their own sacred places, too, although I’ve never stopped to ask those three whelps about it. Point I’m getting at, though, is that all the highland tribes are quite the same in what we do. It’s *the* what *it* do it with and why we do it that’s the important difference.”

Cveta
Performance; Charisma buff
You are now more *charmy*

Cassidy
Taking her inside after sparing
“Dunno why, but I always feel extra alive when I’m done playing with you, ace. It’s not *when* I feel when I’m struck by inspiration, but it’s pretty darn strong, if strong in a different way… damn it, damn it, damn it.

**Comment by aldergames** [comment]
"Fie" is a valid, if antequated word.
