### ISSUE TITLE
Duplicate keys on object in bulltower.js

### ISSUE THREAD

**Issue by VioletVolatile** [AlderArts/foe#422]
In [bulltower.js](https://github.com/AlderArts/foe/blob/master/js/event/outlaws/bulltower.js#L99-L110) the `Outlaws.BullTower` object has the property `SafeLooted` set twice. First to 32 and then it's overwritten to 256.

I'm not sure if this actually breaks anything but it seems like an accident so it's probably worth taking a quick look at it. The first entry can be removed safely if the current behavior is working as expected.

**Comment by aldergames** [comment]
This fix will kinda screw up old saves, but it's not the biggest of deals. It won't change current behavior.

**Comment by VioletVolatile** [comment]
You could keep it backward compatible by removing the first entry instead of the last I think.
