### ISSUE TITLE
PregHandler.IsPregnant() appears to always return false

### ISSUE THREAD

**Issue by ElAcechador** [AlderArts/foe#439]
```
Scenes.Terry.Release()
Scenes.Terry.JeanneTFGrowVag()
Scenes.Terry.Impregnate(terry, player, 10000);
terry.pregHandler.PregnantWombs().forEach(function(elem){console.log(elem.pregnant)})
terry.pregHandler.IsPregnant()
```

`PregnantWombs()` returns an array with a pregnent womb, but `IsPregnant()` returns false regardless.

**Comment by ElAcechador** [comment]
By the looks of it, it used to default to `PregnancyHandler.Slot.Vag` if `opts.slot` was empty.

**Comment by aldergames** [comment]
Not false, no.

`
/*
 * Returns an array of pregnant wombs
 */
PregnancyHandler.prototype.PregnantWombs = function() {
	var ret = [];

	var ent = this.entity;

	var womb = null;
	_.each(ent.AllVags(), function(vag) {
		womb = vag.womb;
		if(womb.pregnant)
			ret.push(womb);
	});
	womb = ent.Butt().womb;
	if(womb.pregnant)
		ret.push(womb);

	return ret;
}
`
That's the PregnantWombs() function (returns an array of all pregnant wombs). With a parameter, IsPregnant returns a specific womb's status. Without a parameter, any womb will do.

**Comment by ElAcechador** [comment]
Well, here's sample code I've ran on a new save, to be sure this wasn't due to some form of state incoherency.

```
Scenes.Terry.Release()
Scenes.Terry.JeanneTFGrowVag()
Scenes.Terry.Impregnate(terry, player, 10000);
terry.pregHandler.PregnantWombs().forEach(function(elem){console.log(elem.pregnant)})
terry.pregHandler.IsPregnant()
```

`PregnantWombs()` returns an array with a pregnent womb, but `IsPregnant()` returns false regardless. What I didn't check in my initial report, however, was that `IsPregnant(PregnancyHandler.Slot.Vag)` also returns false.

**Comment by aldergames** [comment]
Confirmed. I'll look into it. See if it's overloaded somewhere.
