### ISSUE TITLE
Allow for batch creation of potions within the Alchemy menu

### ISSUE THREAD

**Issue by ElAcechador** [AlderArts/foe#442]
Just like stores currently allow you to purchase items in batches of 5 or 10 at once (and then spam those buttons to keep buying the same thing), the alchemy menu should allow for something similar, possibly with an "ALL" option that'd keep brewing for as long as you have the required ingredients.

**Comment by aldergames** [comment]
It'd have to allow for turning on and off this feature tho. I don't want this batch treatment for any other alchemist than the PC.

**Comment by ElAcechador** [comment]
@aldergames : The proposed implementation has a check to see if the current alchemist is the PC and uses the old codepath if that's not the case.
