### ISSUE TITLE
Allow for automated creation of ingredients within the Alchemy menu

### ISSUE THREAD

**Issue by ElAcechador** [AlderArts/foe#443]
The Alchemy system in FoE follows some sort of hierarchy, in that several potions can be crafted with ingredients that can also be crafted. For instance, brewing Anusol requires Gestarium, which can itself be crafted using Estros, which needs Vulpinix. Worst-case scenario : if a player wants to mass-produce Anusol, that's 4 items he needs to go back and forth to make sure he's correctly supplied on each level of his brewing process, which can get quite tedious considering the alchemy menu doesn't allow for mass brewing.

How about offering the player to automatically brew however many lower-tier potions are required for that higher-tier potion automatically and making calculations based on that, instead of letting the player figure those out on his own?

**Comment by aldergames** [comment]
Interesting idea!
