### ISSUE TITLE
Job Unlocks?

### ISSUE THREAD

**Issue by FillerAccount** [AlderArts/foe#446]
In my file, I noticed that Kai and Terry don't have access to certain classes, but Layla has access to every class (besides Acolyte) for some reason? I'm wondering if that's supposed to be the case.

For reference, Kai doesn't have access to: Bruiser, Rogue, Ranger, and Warlock.
Terry doesn't have access to: Bruiser, Elementalist, and Warlock. (and Acolyte.)

**Comment by aldergames** [comment]
This is according to design.
