### ISSUE TITLE
Game gets stuck on Tavros

### ISSUE THREAD

**Issue by Ruoska9** [AlderArts/foe#466]
When I walk past the Bear Man house, I get the introduction with no buttons to proceed. 

![Näyttökuva 2022-11-08 144618](https://user-images.githubusercontent.com/117738590/200567418-ec36d69d-0a63-4676-a18c-d5bc14bce13d.png)

**Comment by ambjoorn94** [comment]
That looks like Trials in Tainted Space, not FoE.
Maybe send the bug report to the forum instead?
