### ISSUE TITLE
Inventory Mangement

### ISSUE THREAD

**Issue by martoko** [AlderArts/foe#65]
Something like sorting items by their type/usage, would be very useful, with the amount of items in this game.

Also some way to keep track of recipes and missing items, something like:
**[Potion Name]**
1/3 *[items]* gathered.
1/3 *[items]* gathered.
1/3 *[items]* gathered.

**Comment by kspriv** [comment]
I noticed an issue with 'Quest' itemtype being included in shop screens. It of course never has items under it though because quest items don't have a price. I don't see a super nice generic solution to this at the moment. Curious if you have thoughts on it?

**Comment by aldergames** [comment]
I'm not 100% sure if the ordering in ItemByType makes a difference, since it's an object, not an array. I think that objects may be unordered sets, but don't quote me on it. Either way, the code looks cleaner.

Had to make a fix, adding a Misc type as default. Toggle debug and choose ITEM in the tent and you'll get most of the items in the game. The "DecoyStick" item didn't have a type, so it caused a crash.

**Comment by kspriv** [comment]
You're correct that objects are technically unordered sets, but I've never run into a browser that doesn't do them in order anyways. So we should be fine - it's at least going to be less random then when being based off of the items array.

Oh, that's my bad on the DecoyStick thing. It looks like I didn't catch items that weren't created with the basic Item constructor(e.g. TFItem/AttackItem). Technically there should be an appropriate item type to describe what those items are, and those item types should be added to to those constructors. I'd rather avoid a "catch all" ItemType in the long run.

**Comment by aldergames** [comment]
Well, neat thing about the catchall is that it's right there in black and white which items don't have a type :P 

And it doesn't even crash!

**Comment by kspriv** [comment]
Touche, good sir.

**Comment by kspriv** [comment]
When I wake up in the morning I want to mess with adding buttons into the regular output area. I think that would have a lot of potential for uncluttering a lot of the item management stuff.

Any ideas? Thoughts? Concerns? etc. :)

**Comment by aldergames** [comment]
I think the time has come to unclutter this issue. How about we list our concerns and issues/todos with the current system and make a new one? We've strayed far enough from the original question.

For me, I have:
* Equip screen
* Combat item screen (same look as the shop/inventory)
* Buy/sell back button resets the button page (if you were on page 2, you'll go back to page 1)

As for buttons, I assume you mean small buttons next to the item in question to sell/sell all etc? Could be worth a try, but I'd keep the current ones too (bigger buttons to press for small screens, +shortcut keys).
